//@ dependencies = ['middle', 'leaf']

package test:common;

world runner {
    import i-runner;

    export run: async func();
}

interface i-runner {
    f: async func();
}

world middle {
    export i-runner;
    import i-middle;
}

interface i-middle {
    f: async func();
}

world leaf {
    export i-middle;
}
