[workspace]
package.version = "0.1.0"
package.edition = "2021"
members = [ "dummy-rt","symmetric_stream","rust-client","dummy-bindgen" ]

[package]
name = "symmetric_executor"
edition.workspace = true
version.workspace = true

[dependencies]
futures = "0.3.31"
libc = "0.2.167"

[dependencies.wit-bindgen]
package = "dummy-rt"
path = "dummy-rt"

[lib]
crate-type = ["cdylib"]

[features]
# always off feature
never = []
# output debugging information
trace = []
