type files = list<tuple<string, string>>

enum lang {
  js,
  rust,
  java,
  wasmtime,
  wasmtime-py,
  c,
  markdown,
}


resource config {
  static new: func() -> config

  render: func(lang: lang, wit: string, import: bool) -> result<files, string>

  set-rust-unchecked: func(unchecked: bool)
  set-wasmtime-tracing: func(unchecked: bool)
  set-wasmtime-custom-error: func(custom: bool)
}
