type files = list<tuple<string, string>>

enum lang {
  js,
  rust,
  java,
  wasmtime,
  wasmtime-py,
  c,
}


record options {
  rust-unchecked: bool,
  wasmtime-tracing: bool,
  import: bool,
}

render: func(lang: lang, wit: string, options: options) -> result<files, string>
