a: func()
b: func(p0: u8, p1: s8, p2: u16, p3: s16, p4: u32, p5: s32, p6: u64, p7: s64) -> tuple<u8, s8, u16, s16, u32, s32, u64, s64>
c: func(p0: float32, p1: float64) -> tuple<float32, float64>
d: func(p0: string) -> string
e: func() -> string
f: func() -> tuple<u32, string, u64>
g: func(p0: u32) -> u32
