// Generated by `wit-bindgen` 0.3.0. DO NOT EDIT!
#ifndef __CPP_NATIVE_BINDINGS_THE_WORLD_H
#define __CPP_NATIVE_BINDINGS_THE_WORLD_H
#define WIT_HOST_DIRECT
#include <cstdint>
#include <string_view>
#include <utility>
#include <wit-host.h>
namespace foo {
namespace foo {
namespace strings {
void A(std::string_view x);
wit::string B();
wit::string C(std::string_view a, std::string_view b);
// export_interface Interface(Id { idx: 0 })
} // namespace strings
} // namespace foo
} // namespace foo
namespace exports {
namespace foo {
namespace foo {
namespace strings {
void A(wit::string x);
wit::guest_owned<std::string_view> B();
wit::guest_owned<std::string_view> C(wit::string a, wit::string b);
} // namespace strings
} // namespace foo
} // namespace foo
} // namespace exports

#endif
