// Generated by `wit-bindgen` 0.3.0. DO NOT EDIT!
#ifndef __CPP_GUEST_BINDINGS_B_H
#define __CPP_GUEST_BINDINGS_B_H
#include "exports-foo-foo-resources-R.h"
#include <cstdint>
#include <utility>
// export_interface Interface(Id { idx: 0 })
namespace exports {
namespace foo {
namespace foo {
namespace resources {
R::Owned Create();
void Consume(R::Owned o);
} // namespace resources
} // namespace foo
} // namespace foo
} // namespace exports

#endif
