// Generated by `wit-bindgen` 0.3.0. DO NOT EDIT!
#ifndef __CPP_GUEST_BINDINGS_A_H
#define __CPP_GUEST_BINDINGS_A_H
#define WIT_SYMMETRIC
#include <cassert>
#include <cstdint>
#include <utility>
#include <wit-guest.h>
namespace foo {
namespace foo {
namespace resources {
class R : public wit::ResourceImportBase {

public:
  ~R();
  R(uint32_t a);
  void Add(uint32_t b) const;
  R(wit::ResourceImportBase &&);
  R(R &&) = default;
  R &operator=(R &&) = default;
};

R Create();
void Consume(R &&o);
} // namespace resources
} // namespace foo
} // namespace foo

#endif
