tuple-arg: function(x: tuple<char, u32>)
tuple-result: function() -> tuple<char, u32>

record empty {}

empty-arg: function(x: empty)
empty-result: function() -> empty

record scalars {
    a: u32,
    b: u32,
}

scalar-arg: function(x: scalars)
scalar-result: function() -> scalars

record really-flags {
    a: bool,
    b: bool,
    c: bool,
    d: bool,
    e: bool,
    f: bool,
    g: bool,
    h: bool,
    i: bool,
}

flags-arg: function(x: really-flags)
flags-result: function() -> really-flags

record aggregates {
    a: scalars,
    b: u32,
    c: empty,
    d: string,
    e: really-flags,
}

aggregate-arg: function(x: aggregates)
aggregate-result: function() -> aggregates
