tuple-arg: func(x: tuple<char, u32>)
tuple-result: func() -> tuple<char, u32>

record empty {}

empty-arg: func(x: empty)
empty-result: func() -> empty

record scalars {
    a: u32,
    b: u32,
}

scalar-arg: func(x: scalars)
scalar-result: func() -> scalars

flags really-flags {
    a,
    b,
    c,
    d,
    e,
    f,
    g,
    h,
    i,
}

flags-arg: func(x: really-flags)
flags-result: func() -> really-flags

record aggregates {
    a: scalars,
    b: u32,
    c: empty,
    d: string,
    e: really-flags,
}

aggregate-arg: func(x: aggregates)
aggregate-result: func() -> aggregates
