roundtrip-u8: function(a: u8) -> u8
roundtrip-s8: function(a: s8) -> s8
roundtrip-u16: function(a: u16) -> u16
roundtrip-s16: function(a: s16) -> s16
roundtrip-u32: function(a: u32) -> u32
roundtrip-s32: function(a: s32) -> s32
roundtrip-u64: function(a: u64) -> u64
roundtrip-s64: function(a: s64) -> s64
roundtrip-float32: function(a: float32) -> float32
roundtrip-float64: function(a: float64) -> float64
roundtrip-char: function(a: char) -> char

set-scalar: function(a: u32)
get-scalar: function() -> u32
