async-no-args: async function()
async-args: async function(a: u32, b: string, c: list<string>)
async-results: async function() -> tuple<u32, string, list<string>>

resource async-resource {
  frob: async function()
}
