package wha:hoo;

interface imports {
  enum fetch-text-error {
    io-error,
    http-error,
  }

  fetch-text: async func(location: string) -> result<string, fetch-text-error>;
}

world core {
  import imports;
}

