// hello 🐱 world

kebab-case: function()

record ludicrous-speed {
  how-fast-are-you-going: u32,
  i-am-going-extremely-slow: u64,
}

foo: function(x: ludicrous-speed)
%function-with-dashes: function()
%function-with-no-weird-characters: function()

apple: function()
apple-pear: function()
apple-pear-grape: function()
garçon: function()
hühnervögel: function()
москва: function()
東-京: function()
garçon-hühnervögel-москва-東-京: function()
a0: function()

%explicit: function()
%explicit-kebab: function()

// Identifiers with the same name as keywords are quoted.
%bool: function()
