// hello 🐱 world

kebab-case: func()

record ludicrous-speed {
  how-fast-are-you-going: u32,
  i-am-going-extremely-slow: u64,
}

foo: func(x: ludicrous-speed)
%function-with-dashes: func()
%function-with-no-weird-characters: func()

apple: func()
apple-pear: func()
apple-pear-grape: func()
garçon: func()
hühnervögel: func()
москва: func()
東-京: func()
garçon-hühnervögel-москва-東-京: func()
a0: func()

%explicit: func()
%explicit-kebab: func()

// Identifiers with the same name as keywords are quoted.
%bool: func()
