package foo:foo;

interface foo-bar {
    record foo{
        // %type: string,
        anything: string
    }

    enum e2 {
        // %type,
        else
    }

    record bar{
        // %type: e2,
        anything: u16
    }

    fetch: func(x: foo) -> result<bar>;
}

world %type {
    import foo-bar;
}
