package foo:foo;

interface store {
  record item {
    key: string,
    value: string,
  }
  get: func(key: string) -> option<string>;
  set: func(key: string, value: string);
}

world implements-mixed {
  import primary: store;
  import backup: store;
  export read-primary: store;
  export read-backup: store;
}
