package foo:foo;

world bindings {
    import component;
}

interface component {
    type value = list<tuple<u32>>;
    type entity = list<tuple<u32, value>>;

    add-components: func(entity: u64, data: entity);
    query-eval: func(q: u64) -> list<tuple<u64, list<value>>>;
}
