package foo:foo;

interface original {
  resource extra-options;
  record options {
    extra: option<borrow<extra-options>>,
  }
}

interface adapter {
  use original.{options};
  variant t { t }
  f: func(x: options, t: t);
}

world root {
  export original;
  export adapter;
}
