package local:demo

interface interface1 {
    variant error {
        some-error
    } 
    record my-record {
        field: u32
    }
    my-func: func() -> result<my-record, error>
    optional: func() -> option<my-record>
}

interface interface2 {
    variant error {
        other-error
    } 
    record my-record {
        other-field: u32
    }
    my-other-func: func() -> result<my-record, error>
    other-optional: func() -> option<my-record>
}

world my-world {
    import interface1
    import interface2
}