package foo:foo;

interface foo-bar {
    record foo{
        %type: string,
        anything: string
    }

    record bar{
        anything: u16
    }

    fetch: func(x: foo) -> result<bar>;
}

world foo-world {
    import foo-bar;
}