resource x

acquire_an_x: function() -> x
receive_an_x: function(val: x)

resource y {
  static some_constructor: function() -> y
  method_on_y: function()
  method_with_param: function(x: u32)
  method_with_result: function() -> string
}
