resource x

acquire-an-x: func() -> x
receive-an-x: func(val: x)

resource y {
  static some-constructor: func() -> y
  method-on-y: func()
  method-with-param: func(x: u32)
  method-with-result: func() -> string
}
