resource x

acquire-an-x: function() -> x
receive-an-x: function(val: x)

resource y {
  static some-constructor: function() -> y
  method-on-y: function()
  method-with-param: function(x: u32)
  method-with-result: function() -> string
}
