interface types {
    record r {
        a: list<u8>,
    }
}

default world the-world {
    import foo: interface {
      use self.types.{r}

      foo: func(data: r)
    }

    export bar: interface {
      use self.types.{r}
    }
}
