interface foo {
  record a {}
  x: func() -> a
}

interface bar {
  use self.foo.{a}
  x: func() -> a
}

default world baz {
  import foo: self.foo
  import bar: self.bar
  import baz: interface {
    use self.foo.{a}
    x: func() -> a
  }
}
