package foo:foo

interface foo {
  record a {}
  x: func() -> a
}

interface bar {
  use foo.{a}
  x: func() -> a
}

world baz {
  import foo
  import bar
  import baz: interface {
    use foo.{a}
    x: func() -> a
  }
}
