f1: func(l: list<u32>)
f2: func() -> list<u32>
// TODO: should re-enable when re-implemented
// f3: func(a: list<u32>, b: list<u32>) -> tuple<list<u32>, list<u32>>
f4: func(l: list<list<u32>>) -> list<list<u32>>
