// Generated by `wit-bindgen` 0.3.0. DO NOT EDIT!
#include "mesh_cpp_native.h"
template <class R> std::map<int32_t, R> wit::ResourceTable<R>::resources;
#include <assert.h>
extern "C" void fooX3AfooX2FresourcesX23X5BdtorX5Dr(uint8_t *);
extern "C" int32_t fooX3AfooX2FresourcesX23X5BconstructorX5Dr(int32_t);
extern "C" void fooX3AfooX2FresourcesX23X5BmethodX5DrX2Eadd(uint8_t *, int32_t);
extern "C" int32_t fooX3AfooX2FresourcesX23create();
extern "C" void fooX3AfooX2FresourcesX23consume(int32_t);
extern "C" void fooX3AfooX2FresourcesX00X5Bresource_dropX5Dr(int32_t arg0) {
  auto ptr = mesh::foo::foo::resources::R::remove_resource(arg0);
  assert(ptr.has_value());
  mesh::foo::foo::resources::R::Dtor(*ptr);
}
extern "C" int32_t fooX3AfooX2FresourcesX00X5BconstructorX5Dr(int32_t arg0) {
  auto result0 = mesh::foo::foo::resources::R::New((uint32_t(arg0)));
  return result0.release()->get_handle();
}
extern "C" void fooX3AfooX2FresourcesX00X5BmethodX5DrX2Eadd(int32_t arg0,
                                                            int32_t arg1) {
  (**mesh::foo::foo::resources::R::lookup_resource(arg0)).Add((uint32_t(arg1)));
}
extern "C" int32_t fooX3AfooX2FresourcesX00create() {
  auto result0 = mesh::foo::foo::resources::Create();
  return result0.release()->get_handle();
}
extern "C" void fooX3AfooX2FresourcesX00consume(int32_t arg0) {
  auto obj0 = mesh::foo::foo::resources::R::remove_resource(arg0);
  assert(obj0.has_value());
  mesh::foo::foo::resources::Consume(
      mesh::foo::foo::resources::R::Owned(*obj0));
}
mesh::exports::foo::foo::resources::R::~R() {
  if (this->rep) {
    fooX3AfooX2FresourcesX23X5BdtorX5Dr(this->rep);
  }
}
mesh::exports::foo::foo::resources::R::R(uint32_t a) {
  auto ret = fooX3AfooX2FresourcesX23X5BconstructorX5Dr((int32_t(a)));
  wit::ResourceExportBase retobj = wit::ResourceExportBase{ret};
  this->index = retobj.get_handle();
  this->rep = retobj.take_rep();
}
void mesh::exports::foo::foo::resources::R::Add(uint32_t b) const {
  fooX3AfooX2FresourcesX23X5BmethodX5DrX2Eadd((*this).get_rep(), (int32_t(b)));
}
mesh::exports::foo::foo::resources::R::R(wit::ResourceExportBase &&b)
    : wit::ResourceExportBase(std::move(b)) {}
extern "C" int32_t
X5BexportX5DfooX3AfooX2FresourcesX00X5Bresource_newX5Dr(uint8_t *arg0) {
  return mesh::exports::foo::foo::resources::R::store_resource(std::move(arg0));
}
extern "C" uint8_t *
X5BexportX5DfooX3AfooX2FresourcesX00X5Bresource_repX5Dr(int32_t arg0) {
  return *mesh::exports::foo::foo::resources::R::lookup_resource(arg0);
}
extern "C" void
X5BexportX5DfooX3AfooX2FresourcesX00X5Bresource_dropX5Dr(int32_t arg0) {
  auto obj = mesh::exports::foo::foo::resources::R::remove_resource(arg0);
  fooX3AfooX2FresourcesX23X5BdtorX5Dr(*obj);
}
mesh::exports::foo::foo::resources::R
mesh::exports::foo::foo::resources::Create() {
  auto ret = fooX3AfooX2FresourcesX23create();
  return wit::ResourceExportBase{ret};
}
void mesh::exports::foo::foo::resources::Consume(R &&o) {
  auto rep0 = o.take_rep();
  fooX3AfooX2FresourcesX23consume(o.get_handle());
}

// Component Adapters
