// Generated by `wit-bindgen` 0.3.0. DO NOT EDIT!
#ifndef __CPP_GUEST_BINDINGS_THE_WORLD_H
#define __CPP_GUEST_BINDINGS_THE_WORLD_H
#define WIT_SYMMETRIC
#include <cstdint>
#include <string_view>
#include <utility>
#include <wit-guest.h>
namespace foo {
namespace foo {
namespace strings {
void A(std::string_view x);
wit::string B();
wit::string C(std::string_view a, std::string_view b);
// export_interface Interface(Id { idx: 0 })
} // namespace strings
} // namespace foo
} // namespace foo
namespace exports {
namespace foo {
namespace foo {
namespace strings {
void A(std::string_view x);
wit::string B();
wit::string C(std::string_view a, std::string_view b);
} // namespace strings
} // namespace foo
} // namespace foo
} // namespace exports

#endif
