(component
  (type (;0;) (func))
  (type (;1;) (func (result string)))
  (type (;2;) (func (param "x" string) (result string)))
  (module (;0;)
    (type (;0;) (func))
    (type (;1;) (func (result i32)))
    (type (;2;) (func (param i32 i32) (result i32)))
    (type (;3;) (func (param i32 i32 i32 i32) (result i32)))
    (type (;4;) (func (param i32 i32 i32)))
    (func (;0;) (type 0)
      unreachable
    )
    (func (;1;) (type 1) (result i32)
      unreachable
    )
    (func (;2;) (type 2) (param i32 i32) (result i32)
      unreachable
    )
    (func (;3;) (type 3) (param i32 i32 i32 i32) (result i32)
      unreachable
    )
    (func (;4;) (type 4) (param i32 i32 i32)
      unreachable
    )
    (memory (;0;) 1)
    (export "memory" (memory 0))
    (export "a" (func 0))
    (export "b" (func 1))
    (export "c" (func 2))
    (export "canonical_abi_realloc" (func 3))
    (export "canonical_abi_free" (func 4))
  )
  (instance (;0;) (instantiate (module 0)))
  (alias export (instance 0) "a" (func (;0;)))
  (alias export (instance 0) "b" (func (;1;)))
  (alias export (instance 0) "c" (func (;2;)))
  (func (;3;) (canon.lift (type 0) utf8 (into (instance 0)) (func 0)))
  (func (;4;) (canon.lift (type 1) utf8 (into (instance 0)) (func 1)))
  (func (;5;) (canon.lift (type 2) utf8 (into (instance 0)) (func 2)))
  (export "a" (func 3))
  (export "b" (func 4))
  (export "c" (func 5))
)