// Generated by `wit-bindgen` 0.36.0. DO NOT EDIT!
// Options used:
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod symmetric {
        pub mod runtime {
            /// This interface will only work with symmetric ABI (shared everything),
            /// it can't be composed with the canonical ABI
            /// Asynchronous executor functionality for symmetric ABI
            #[allow(dead_code, clippy::all)]
            pub mod symmetric_executor {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() =
                    super::super::super::super::__link_custom_section_describing_imports;

                use super::super::super::super::_rt;
                /// These pseudo-resources are just used to
                /// pass pointers to register
                /// This wraps a user provided function of type
                /// `fn (callback-data) -> callback-state`

                #[derive(Debug)]
                #[repr(transparent)]
                pub struct CallbackFunction {
                    handle: _rt::Resource<CallbackFunction>,
                }

                type _CallbackFunctionRep<T> = Option<T>;

                impl CallbackFunction {
                    /// Creates a new resource from the specified representation.
                    ///
                    /// This function will create a new resource handle by moving `val` onto
                    /// the heap and then passing that heap pointer to the component model to
                    /// create a handle. The owned handle is then returned as `CallbackFunction`.
                    pub fn new<T: GuestCallbackFunction>(val: T) -> Self {
                        Self::type_guard::<T>();
                        let val: _CallbackFunctionRep<T> = Some(val);
                        let ptr: *mut _CallbackFunctionRep<T> =
                            _rt::Box::into_raw(_rt::Box::new(val));
                        unsafe { Self::from_handle(T::_resource_new(ptr.cast())) }
                    }

                    /// Gets access to the underlying `T` which represents this resource.
                    pub fn get<T: GuestCallbackFunction>(&self) -> &T {
                        let ptr = unsafe { &*self.as_ptr::<T>() };
                        ptr.as_ref().unwrap()
                    }

                    /// Gets mutable access to the underlying `T` which represents this
                    /// resource.
                    pub fn get_mut<T: GuestCallbackFunction>(&mut self) -> &mut T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.as_mut().unwrap()
                    }

                    /// Consumes this resource and returns the underlying `T`.
                    pub fn into_inner<T: GuestCallbackFunction>(self) -> T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.take().unwrap()
                    }

                    #[doc(hidden)]
                    pub unsafe fn from_handle(handle: usize) -> Self {
                        Self {
                            handle: _rt::Resource::from_handle(handle),
                        }
                    }

                    #[doc(hidden)]
                    pub fn take_handle(&self) -> usize {
                        _rt::Resource::take_handle(&self.handle)
                    }

                    #[doc(hidden)]
                    pub fn handle(&self) -> usize {
                        _rt::Resource::handle(&self.handle)
                    }

                    // It's theoretically possible to implement the `GuestCallbackFunction` trait twice
                    // so guard against using it with two different types here.
                    #[doc(hidden)]
                    fn type_guard<T: 'static>() {
                        use core::any::TypeId;
                        static mut LAST_TYPE: Option<TypeId> = None;
                        unsafe {
                            assert!(!cfg!(target_feature = "atomics"));
                            let id = TypeId::of::<T>();
                            match LAST_TYPE {
                                Some(ty) => assert!(
                                    ty == id,
                                    "cannot use two types with this resource type"
                                ),
                                None => LAST_TYPE = Some(id),
                            }
                        }
                    }

                    #[doc(hidden)]
                    pub unsafe fn dtor<T: 'static>(handle: *mut u8) {
                        Self::type_guard::<T>();
                        let _ = _rt::Box::from_raw(handle as *mut _CallbackFunctionRep<T>);
                    }

                    fn as_ptr<T: GuestCallbackFunction>(&self) -> *mut _CallbackFunctionRep<T> {
                        CallbackFunction::type_guard::<T>();
                        T::_resource_rep(self.handle()).cast()
                    }
                }

                /// A borrowed version of [`CallbackFunction`] which represents a borrowed value
                /// with the lifetime `'a`.
                #[derive(Debug)]
                #[repr(transparent)]
                pub struct CallbackFunctionBorrow<'a> {
                    rep: *mut u8,
                    _marker: core::marker::PhantomData<&'a CallbackFunction>,
                }

                impl<'a> CallbackFunctionBorrow<'a> {
                    #[doc(hidden)]
                    pub unsafe fn lift(rep: usize) -> Self {
                        Self {
                            rep: rep as *mut u8,
                            _marker: core::marker::PhantomData,
                        }
                    }

                    /// Gets access to the underlying `T` in this resource.
                    pub fn get<T: GuestCallbackFunction>(&self) -> &T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.as_ref().unwrap()
                    }

                    // NB: mutable access is not allowed due to the component model allowing
                    // multiple borrows of the same resource.

                    fn as_ptr<T: 'static>(&self) -> *mut _CallbackFunctionRep<T> {
                        CallbackFunction::type_guard::<T>();
                        self.rep.cast()
                    }
                }

                unsafe impl _rt::WasmResource for CallbackFunction {
                    #[inline]
                    unsafe fn drop(_handle: usize) {
                        {
                            #[link(
                                wasm_import_module = "symmetric:runtime/symmetric-executor@0.1.0"
                            )]
                            extern "C" {
                                #[cfg_attr(
                                    target_arch = "wasm32",
                                    link_name = "[resource-drop]callback-function"
                                )]
                                fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E1X2E0X00X5Bresource_dropX5Dcallback_function(
                                    _: usize,
                                );
                            }

                            symmetricX3AruntimeX2Fsymmetric_executorX400X2E1X2E0X00X5Bresource_dropX5Dcallback_function(_handle);
                        }
                    }
                }

                /// This wraps opaque user data, freed by the callback once
                /// it returns ready

                #[derive(Debug)]
                #[repr(transparent)]
                pub struct CallbackData {
                    handle: _rt::Resource<CallbackData>,
                }

                type _CallbackDataRep<T> = Option<T>;

                impl CallbackData {
                    /// Creates a new resource from the specified representation.
                    ///
                    /// This function will create a new resource handle by moving `val` onto
                    /// the heap and then passing that heap pointer to the component model to
                    /// create a handle. The owned handle is then returned as `CallbackData`.
                    pub fn new<T: GuestCallbackData>(val: T) -> Self {
                        Self::type_guard::<T>();
                        let val: _CallbackDataRep<T> = Some(val);
                        let ptr: *mut _CallbackDataRep<T> = _rt::Box::into_raw(_rt::Box::new(val));
                        unsafe { Self::from_handle(T::_resource_new(ptr.cast())) }
                    }

                    /// Gets access to the underlying `T` which represents this resource.
                    pub fn get<T: GuestCallbackData>(&self) -> &T {
                        let ptr = unsafe { &*self.as_ptr::<T>() };
                        ptr.as_ref().unwrap()
                    }

                    /// Gets mutable access to the underlying `T` which represents this
                    /// resource.
                    pub fn get_mut<T: GuestCallbackData>(&mut self) -> &mut T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.as_mut().unwrap()
                    }

                    /// Consumes this resource and returns the underlying `T`.
                    pub fn into_inner<T: GuestCallbackData>(self) -> T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.take().unwrap()
                    }

                    #[doc(hidden)]
                    pub unsafe fn from_handle(handle: usize) -> Self {
                        Self {
                            handle: _rt::Resource::from_handle(handle),
                        }
                    }

                    #[doc(hidden)]
                    pub fn take_handle(&self) -> usize {
                        _rt::Resource::take_handle(&self.handle)
                    }

                    #[doc(hidden)]
                    pub fn handle(&self) -> usize {
                        _rt::Resource::handle(&self.handle)
                    }

                    // It's theoretically possible to implement the `GuestCallbackData` trait twice
                    // so guard against using it with two different types here.
                    #[doc(hidden)]
                    fn type_guard<T: 'static>() {
                        use core::any::TypeId;
                        static mut LAST_TYPE: Option<TypeId> = None;
                        unsafe {
                            assert!(!cfg!(target_feature = "atomics"));
                            let id = TypeId::of::<T>();
                            match LAST_TYPE {
                                Some(ty) => assert!(
                                    ty == id,
                                    "cannot use two types with this resource type"
                                ),
                                None => LAST_TYPE = Some(id),
                            }
                        }
                    }

                    #[doc(hidden)]
                    pub unsafe fn dtor<T: 'static>(handle: *mut u8) {
                        Self::type_guard::<T>();
                        let _ = _rt::Box::from_raw(handle as *mut _CallbackDataRep<T>);
                    }

                    fn as_ptr<T: GuestCallbackData>(&self) -> *mut _CallbackDataRep<T> {
                        CallbackData::type_guard::<T>();
                        T::_resource_rep(self.handle()).cast()
                    }
                }

                /// A borrowed version of [`CallbackData`] which represents a borrowed value
                /// with the lifetime `'a`.
                #[derive(Debug)]
                #[repr(transparent)]
                pub struct CallbackDataBorrow<'a> {
                    rep: *mut u8,
                    _marker: core::marker::PhantomData<&'a CallbackData>,
                }

                impl<'a> CallbackDataBorrow<'a> {
                    #[doc(hidden)]
                    pub unsafe fn lift(rep: usize) -> Self {
                        Self {
                            rep: rep as *mut u8,
                            _marker: core::marker::PhantomData,
                        }
                    }

                    /// Gets access to the underlying `T` in this resource.
                    pub fn get<T: GuestCallbackData>(&self) -> &T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.as_ref().unwrap()
                    }

                    // NB: mutable access is not allowed due to the component model allowing
                    // multiple borrows of the same resource.

                    fn as_ptr<T: 'static>(&self) -> *mut _CallbackDataRep<T> {
                        CallbackData::type_guard::<T>();
                        self.rep.cast()
                    }
                }

                unsafe impl _rt::WasmResource for CallbackData {
                    #[inline]
                    unsafe fn drop(_handle: usize) {
                        {
                            #[link(
                                wasm_import_module = "symmetric:runtime/symmetric-executor@0.1.0"
                            )]
                            extern "C" {
                                #[cfg_attr(
                                    target_arch = "wasm32",
                                    link_name = "[resource-drop]callback-data"
                                )]
                                fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E1X2E0X00X5Bresource_dropX5Dcallback_data(
                                    _: usize,
                                );
                            }

                            symmetricX3AruntimeX2Fsymmetric_executorX400X2E1X2E0X00X5Bresource_dropX5Dcallback_data(_handle);
                        }
                    }
                }

                /// The receiving side of an event

                #[derive(Debug)]
                #[repr(transparent)]
                pub struct EventSubscription {
                    handle: _rt::Resource<EventSubscription>,
                }

                type _EventSubscriptionRep<T> = Option<T>;

                impl EventSubscription {
                    /// Creates a new resource from the specified representation.
                    ///
                    /// This function will create a new resource handle by moving `val` onto
                    /// the heap and then passing that heap pointer to the component model to
                    /// create a handle. The owned handle is then returned as `EventSubscription`.
                    pub fn new<T: GuestEventSubscription>(val: T) -> Self {
                        Self::type_guard::<T>();
                        let val: _EventSubscriptionRep<T> = Some(val);
                        let ptr: *mut _EventSubscriptionRep<T> =
                            _rt::Box::into_raw(_rt::Box::new(val));
                        unsafe { Self::from_handle(T::_resource_new(ptr.cast())) }
                    }

                    /// Gets access to the underlying `T` which represents this resource.
                    pub fn get<T: GuestEventSubscription>(&self) -> &T {
                        let ptr = unsafe { &*self.as_ptr::<T>() };
                        ptr.as_ref().unwrap()
                    }

                    /// Gets mutable access to the underlying `T` which represents this
                    /// resource.
                    pub fn get_mut<T: GuestEventSubscription>(&mut self) -> &mut T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.as_mut().unwrap()
                    }

                    /// Consumes this resource and returns the underlying `T`.
                    pub fn into_inner<T: GuestEventSubscription>(self) -> T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.take().unwrap()
                    }

                    #[doc(hidden)]
                    pub unsafe fn from_handle(handle: usize) -> Self {
                        Self {
                            handle: _rt::Resource::from_handle(handle),
                        }
                    }

                    #[doc(hidden)]
                    pub fn take_handle(&self) -> usize {
                        _rt::Resource::take_handle(&self.handle)
                    }

                    #[doc(hidden)]
                    pub fn handle(&self) -> usize {
                        _rt::Resource::handle(&self.handle)
                    }

                    // It's theoretically possible to implement the `GuestEventSubscription` trait twice
                    // so guard against using it with two different types here.
                    #[doc(hidden)]
                    fn type_guard<T: 'static>() {
                        use core::any::TypeId;
                        static mut LAST_TYPE: Option<TypeId> = None;
                        unsafe {
                            assert!(!cfg!(target_feature = "atomics"));
                            let id = TypeId::of::<T>();
                            match LAST_TYPE {
                                Some(ty) => assert!(
                                    ty == id,
                                    "cannot use two types with this resource type"
                                ),
                                None => LAST_TYPE = Some(id),
                            }
                        }
                    }

                    #[doc(hidden)]
                    pub unsafe fn dtor<T: 'static>(handle: *mut u8) {
                        Self::type_guard::<T>();
                        let _ = _rt::Box::from_raw(handle as *mut _EventSubscriptionRep<T>);
                    }

                    fn as_ptr<T: GuestEventSubscription>(&self) -> *mut _EventSubscriptionRep<T> {
                        EventSubscription::type_guard::<T>();
                        T::_resource_rep(self.handle()).cast()
                    }
                }

                /// A borrowed version of [`EventSubscription`] which represents a borrowed value
                /// with the lifetime `'a`.
                #[derive(Debug)]
                #[repr(transparent)]
                pub struct EventSubscriptionBorrow<'a> {
                    rep: *mut u8,
                    _marker: core::marker::PhantomData<&'a EventSubscription>,
                }

                impl<'a> EventSubscriptionBorrow<'a> {
                    #[doc(hidden)]
                    pub unsafe fn lift(rep: usize) -> Self {
                        Self {
                            rep: rep as *mut u8,
                            _marker: core::marker::PhantomData,
                        }
                    }

                    /// Gets access to the underlying `T` in this resource.
                    pub fn get<T: GuestEventSubscription>(&self) -> &T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.as_ref().unwrap()
                    }

                    // NB: mutable access is not allowed due to the component model allowing
                    // multiple borrows of the same resource.

                    fn as_ptr<T: 'static>(&self) -> *mut _EventSubscriptionRep<T> {
                        EventSubscription::type_guard::<T>();
                        self.rep.cast()
                    }
                }

                unsafe impl _rt::WasmResource for EventSubscription {
                    #[inline]
                    unsafe fn drop(_handle: usize) {
                        {
                            #[link(
                                wasm_import_module = "symmetric:runtime/symmetric-executor@0.1.0"
                            )]
                            extern "C" {
                                #[cfg_attr(
                                    target_arch = "wasm32",
                                    link_name = "[resource-drop]event-subscription"
                                )]
                                fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E1X2E0X00X5Bresource_dropX5Devent_subscription(
                                    _: usize,
                                );
                            }

                            symmetricX3AruntimeX2Fsymmetric_executorX400X2E1X2E0X00X5Bresource_dropX5Devent_subscription(_handle);
                        }
                    }
                }

                /// A user controlled event

                #[derive(Debug)]
                #[repr(transparent)]
                pub struct EventGenerator {
                    handle: _rt::Resource<EventGenerator>,
                }

                type _EventGeneratorRep<T> = Option<T>;

                impl EventGenerator {
                    /// Creates a new resource from the specified representation.
                    ///
                    /// This function will create a new resource handle by moving `val` onto
                    /// the heap and then passing that heap pointer to the component model to
                    /// create a handle. The owned handle is then returned as `EventGenerator`.
                    pub fn new<T: GuestEventGenerator>(val: T) -> Self {
                        Self::type_guard::<T>();
                        let val: _EventGeneratorRep<T> = Some(val);
                        let ptr: *mut _EventGeneratorRep<T> =
                            _rt::Box::into_raw(_rt::Box::new(val));
                        unsafe { Self::from_handle(T::_resource_new(ptr.cast())) }
                    }

                    /// Gets access to the underlying `T` which represents this resource.
                    pub fn get<T: GuestEventGenerator>(&self) -> &T {
                        let ptr = unsafe { &*self.as_ptr::<T>() };
                        ptr.as_ref().unwrap()
                    }

                    /// Gets mutable access to the underlying `T` which represents this
                    /// resource.
                    pub fn get_mut<T: GuestEventGenerator>(&mut self) -> &mut T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.as_mut().unwrap()
                    }

                    /// Consumes this resource and returns the underlying `T`.
                    pub fn into_inner<T: GuestEventGenerator>(self) -> T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.take().unwrap()
                    }

                    #[doc(hidden)]
                    pub unsafe fn from_handle(handle: usize) -> Self {
                        Self {
                            handle: _rt::Resource::from_handle(handle),
                        }
                    }

                    #[doc(hidden)]
                    pub fn take_handle(&self) -> usize {
                        _rt::Resource::take_handle(&self.handle)
                    }

                    #[doc(hidden)]
                    pub fn handle(&self) -> usize {
                        _rt::Resource::handle(&self.handle)
                    }

                    // It's theoretically possible to implement the `GuestEventGenerator` trait twice
                    // so guard against using it with two different types here.
                    #[doc(hidden)]
                    fn type_guard<T: 'static>() {
                        use core::any::TypeId;
                        static mut LAST_TYPE: Option<TypeId> = None;
                        unsafe {
                            assert!(!cfg!(target_feature = "atomics"));
                            let id = TypeId::of::<T>();
                            match LAST_TYPE {
                                Some(ty) => assert!(
                                    ty == id,
                                    "cannot use two types with this resource type"
                                ),
                                None => LAST_TYPE = Some(id),
                            }
                        }
                    }

                    #[doc(hidden)]
                    pub unsafe fn dtor<T: 'static>(handle: *mut u8) {
                        Self::type_guard::<T>();
                        let _ = _rt::Box::from_raw(handle as *mut _EventGeneratorRep<T>);
                    }

                    fn as_ptr<T: GuestEventGenerator>(&self) -> *mut _EventGeneratorRep<T> {
                        EventGenerator::type_guard::<T>();
                        T::_resource_rep(self.handle()).cast()
                    }
                }

                /// A borrowed version of [`EventGenerator`] which represents a borrowed value
                /// with the lifetime `'a`.
                #[derive(Debug)]
                #[repr(transparent)]
                pub struct EventGeneratorBorrow<'a> {
                    rep: *mut u8,
                    _marker: core::marker::PhantomData<&'a EventGenerator>,
                }

                impl<'a> EventGeneratorBorrow<'a> {
                    #[doc(hidden)]
                    pub unsafe fn lift(rep: usize) -> Self {
                        Self {
                            rep: rep as *mut u8,
                            _marker: core::marker::PhantomData,
                        }
                    }

                    /// Gets access to the underlying `T` in this resource.
                    pub fn get<T: GuestEventGenerator>(&self) -> &T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.as_ref().unwrap()
                    }

                    // NB: mutable access is not allowed due to the component model allowing
                    // multiple borrows of the same resource.

                    fn as_ptr<T: 'static>(&self) -> *mut _EventGeneratorRep<T> {
                        EventGenerator::type_guard::<T>();
                        self.rep.cast()
                    }
                }

                unsafe impl _rt::WasmResource for EventGenerator {
                    #[inline]
                    unsafe fn drop(_handle: usize) {
                        {
                            #[link(
                                wasm_import_module = "symmetric:runtime/symmetric-executor@0.1.0"
                            )]
                            extern "C" {
                                #[cfg_attr(
                                    target_arch = "wasm32",
                                    link_name = "[resource-drop]event-generator"
                                )]
                                fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E1X2E0X00X5Bresource_dropX5Devent_generator(
                                    _: usize,
                                );
                            }

                            symmetricX3AruntimeX2Fsymmetric_executorX400X2E1X2E0X00X5Bresource_dropX5Devent_generator(_handle);
                        }
                    }
                }

                /// Return value of an async call, lowest bit encoding
                #[repr(u8)]
                #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
                pub enum CallStatus {
                    /// For symmetric this means that processing has started, parameters should still remain valid until null,
                    /// params-read = non-null, results-written,done = null
                    Started,
                    /// For symmetric: Retry the call (temporarily out of memory)
                    NotStarted,
                }
                impl ::core::fmt::Debug for CallStatus {
                    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                        match self {
                            CallStatus::Started => f.debug_tuple("CallStatus::Started").finish(),
                            CallStatus::NotStarted => {
                                f.debug_tuple("CallStatus::NotStarted").finish()
                            }
                        }
                    }
                }

                impl CallStatus {
                    #[doc(hidden)]
                    pub unsafe fn _lift(val: u8) -> CallStatus {
                        if !cfg!(debug_assertions) {
                            return ::core::mem::transmute(val);
                        }

                        match val {
                            0 => CallStatus::Started,
                            1 => CallStatus::NotStarted,

                            _ => panic!("invalid enum discriminant"),
                        }
                    }
                }

                /// Return value of an event callback
                #[repr(u8)]
                #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
                pub enum CallbackState {
                    /// Call the function again
                    Pending,
                    /// The function has completed, all results are written, data is freed,
                    /// calling the function again is not permitted as data became invalid!
                    Ready,
                }
                impl ::core::fmt::Debug for CallbackState {
                    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                        match self {
                            CallbackState::Pending => {
                                f.debug_tuple("CallbackState::Pending").finish()
                            }
                            CallbackState::Ready => f.debug_tuple("CallbackState::Ready").finish(),
                        }
                    }
                }

                impl CallbackState {
                    #[doc(hidden)]
                    pub unsafe fn _lift(val: u8) -> CallbackState {
                        if !cfg!(debug_assertions) {
                            return ::core::mem::transmute(val);
                        }

                        match val {
                            0 => CallbackState::Pending,
                            1 => CallbackState::Ready,

                            _ => panic!("invalid enum discriminant"),
                        }
                    }
                }

                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_event_subscription_ready_cabi<
                    T: GuestEventSubscription,
                >(
                    arg0: *mut u8,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")]
                    _rt::run_ctors_once();
                    let result0 = T::ready(EventSubscriptionBorrow::lift(arg0 as usize).get());
                    match result0 {
                        true => 1,
                        false => 0,
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_static_event_subscription_from_timeout_cabi<
                    T: GuestEventSubscription,
                >(
                    arg0: i64,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")]
                    _rt::run_ctors_once();
                    let result0 = T::from_timeout(arg0 as u64);
                    (result0).take_handle() as *mut u8
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_event_subscription_dup_cabi<
                    T: GuestEventSubscription,
                >(
                    arg0: *mut u8,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")]
                    _rt::run_ctors_once();
                    let result0 = T::dup(EventSubscriptionBorrow::lift(arg0 as usize).get());
                    (result0).take_handle() as *mut u8
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_event_subscription_reset_cabi<
                    T: GuestEventSubscription,
                >(
                    arg0: *mut u8,
                ) {
                    #[cfg(target_arch = "wasm32")]
                    _rt::run_ctors_once();
                    T::reset(EventSubscriptionBorrow::lift(arg0 as usize).get());
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_constructor_event_generator_cabi<T: GuestEventGenerator>(
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")]
                    _rt::run_ctors_once();
                    let result0 = EventGenerator::new(T::new());
                    (result0).take_handle() as *mut u8
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_event_generator_subscribe_cabi<
                    T: GuestEventGenerator,
                >(
                    arg0: *mut u8,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")]
                    _rt::run_ctors_once();
                    let result0 = T::subscribe(EventGeneratorBorrow::lift(arg0 as usize).get());
                    (result0).take_handle() as *mut u8
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_event_generator_activate_cabi<
                    T: GuestEventGenerator,
                >(
                    arg0: *mut u8,
                ) {
                    #[cfg(target_arch = "wasm32")]
                    _rt::run_ctors_once();
                    T::activate(EventGeneratorBorrow::lift(arg0 as usize).get());
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_run_cabi<T: Guest>() {
                    #[cfg(target_arch = "wasm32")]
                    _rt::run_ctors_once();
                    T::run();
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_register_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: *mut u8,
                    arg2: *mut u8,
                ) {
                    #[cfg(target_arch = "wasm32")]
                    _rt::run_ctors_once();
                    T::register(
                        EventSubscription::from_handle(arg0 as usize),
                        CallbackFunction::from_handle(arg1 as usize),
                        CallbackData::from_handle(arg2 as usize),
                    );
                }
                pub trait Guest {
                    type CallbackFunction: GuestCallbackFunction;
                    type CallbackData: GuestCallbackData;
                    type EventSubscription: GuestEventSubscription;
                    type EventGenerator: GuestEventGenerator;
                    /// Wait until all registered events have completed
                    fn run() -> ();
                    /// Register a callback for an event
                    fn register(
                        trigger: EventSubscription,
                        callback: CallbackFunction,
                        data: CallbackData,
                    ) -> ();
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_drop_callbackFunction_cabi<T: GuestCallbackFunction>(
                    arg0: usize,
                ) {
                    #[cfg(target_arch = "wasm32")]
                    _rt::run_ctors_once();
                    CallbackFunction::dtor::<T>(arg0 as *mut u8);
                }
                pub trait GuestCallbackFunction: 'static {
                    #[doc(hidden)]
                    unsafe fn _resource_new(val: *mut u8) -> usize
                    where
                        Self: Sized,
                    {
                        val as usize
                    }

                    #[doc(hidden)]
                    fn _resource_rep(handle: usize) -> *mut u8
                    where
                        Self: Sized,
                    {
                        handle as *mut u8
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_drop_callbackData_cabi<T: GuestCallbackData>(arg0: usize) {
                    #[cfg(target_arch = "wasm32")]
                    _rt::run_ctors_once();
                    CallbackData::dtor::<T>(arg0 as *mut u8);
                }
                pub trait GuestCallbackData: 'static {
                    #[doc(hidden)]
                    unsafe fn _resource_new(val: *mut u8) -> usize
                    where
                        Self: Sized,
                    {
                        val as usize
                    }

                    #[doc(hidden)]
                    fn _resource_rep(handle: usize) -> *mut u8
                    where
                        Self: Sized,
                    {
                        handle as *mut u8
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_drop_eventSubscription_cabi<T: GuestEventSubscription>(
                    arg0: usize,
                ) {
                    #[cfg(target_arch = "wasm32")]
                    _rt::run_ctors_once();
                    EventSubscription::dtor::<T>(arg0 as *mut u8);
                }
                pub trait GuestEventSubscription: 'static {
                    #[doc(hidden)]
                    unsafe fn _resource_new(val: *mut u8) -> usize
                    where
                        Self: Sized,
                    {
                        val as usize
                    }

                    #[doc(hidden)]
                    fn _resource_rep(handle: usize) -> *mut u8
                    where
                        Self: Sized,
                    {
                        handle as *mut u8
                    }

                    /// Whether the event is active (used by poll implementation)
                    fn ready(&self) -> bool;
                    /// Create a timeout event
                    fn from_timeout(nanoseconds: u64) -> EventSubscription;
                    /// Duplicate the subscription (e.g. for repeated callback registering, same cost as subscribe)
                    fn dup(&self) -> EventSubscription;
                    /// Reset subscription to be inactive, only next trigger will ready it
                    fn reset(&self) -> ();
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_drop_eventGenerator_cabi<T: GuestEventGenerator>(
                    arg0: usize,
                ) {
                    #[cfg(target_arch = "wasm32")]
                    _rt::run_ctors_once();
                    EventGenerator::dtor::<T>(arg0 as *mut u8);
                }
                pub trait GuestEventGenerator: 'static {
                    #[doc(hidden)]
                    unsafe fn _resource_new(val: *mut u8) -> usize
                    where
                        Self: Sized,
                    {
                        val as usize
                    }

                    #[doc(hidden)]
                    fn _resource_rep(handle: usize) -> *mut u8
                    where
                        Self: Sized,
                    {
                        handle as *mut u8
                    }

                    fn new() -> Self;
                    /// Get the receiving side (to pass to other parts of the program)
                    fn subscribe(&self) -> EventSubscription;
                    /// Trigger all subscribers
                    fn activate(&self) -> ();
                }
                #[doc(hidden)]

                macro_rules! __export_symmetric_runtime_symmetric_executor_0_1_0_cabi{
  ($ty:ident with_types_in $($path_to_types:tt)*) => (const _: () = {

    #[cfg_attr(target_arch = "wasm32", export_name = "[method]event-subscription.ready")]
    #[cfg_attr(not(target_arch = "wasm32"), no_mangle)]
    unsafe extern "C" fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E1X2E0X00X5BmethodX5Devent_subscriptionX2Eready(arg0: *mut u8,) -> i32 {
      $($path_to_types)*::_export_method_event_subscription_ready_cabi::<<$ty as $($path_to_types)*::Guest>::EventSubscription>(arg0)
    }
    #[cfg_attr(target_arch = "wasm32", export_name = "[static]event-subscription.from-timeout")]
    #[cfg_attr(not(target_arch = "wasm32"), no_mangle)]
    unsafe extern "C" fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E1X2E0X00X5BstaticX5Devent_subscriptionX2Efrom_timeout(arg0: i64,) -> *mut u8 {
      $($path_to_types)*::_export_static_event_subscription_from_timeout_cabi::<<$ty as $($path_to_types)*::Guest>::EventSubscription>(arg0)
    }
    #[cfg_attr(target_arch = "wasm32", export_name = "[method]event-subscription.dup")]
    #[cfg_attr(not(target_arch = "wasm32"), no_mangle)]
    unsafe extern "C" fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E1X2E0X00X5BmethodX5Devent_subscriptionX2Edup(arg0: *mut u8,) -> *mut u8 {
      $($path_to_types)*::_export_method_event_subscription_dup_cabi::<<$ty as $($path_to_types)*::Guest>::EventSubscription>(arg0)
    }
    #[cfg_attr(target_arch = "wasm32", export_name = "[method]event-subscription.reset")]
    #[cfg_attr(not(target_arch = "wasm32"), no_mangle)]
    unsafe extern "C" fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E1X2E0X00X5BmethodX5Devent_subscriptionX2Ereset(arg0: *mut u8,) {
      $($path_to_types)*::_export_method_event_subscription_reset_cabi::<<$ty as $($path_to_types)*::Guest>::EventSubscription>(arg0)
    }
    #[cfg_attr(target_arch = "wasm32", export_name = "[constructor]event-generator")]
    #[cfg_attr(not(target_arch = "wasm32"), no_mangle)]
    unsafe extern "C" fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E1X2E0X00X5BconstructorX5Devent_generator() -> *mut u8 {
      $($path_to_types)*::_export_constructor_event_generator_cabi::<<$ty as $($path_to_types)*::Guest>::EventGenerator>()
    }
    #[cfg_attr(target_arch = "wasm32", export_name = "[method]event-generator.subscribe")]
    #[cfg_attr(not(target_arch = "wasm32"), no_mangle)]
    unsafe extern "C" fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E1X2E0X00X5BmethodX5Devent_generatorX2Esubscribe(arg0: *mut u8,) -> *mut u8 {
      $($path_to_types)*::_export_method_event_generator_subscribe_cabi::<<$ty as $($path_to_types)*::Guest>::EventGenerator>(arg0)
    }
    #[cfg_attr(target_arch = "wasm32", export_name = "[method]event-generator.activate")]
    #[cfg_attr(not(target_arch = "wasm32"), no_mangle)]
    unsafe extern "C" fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E1X2E0X00X5BmethodX5Devent_generatorX2Eactivate(arg0: *mut u8,) {
      $($path_to_types)*::_export_method_event_generator_activate_cabi::<<$ty as $($path_to_types)*::Guest>::EventGenerator>(arg0)
    }
    #[cfg_attr(target_arch = "wasm32", export_name = "run")]
    #[cfg_attr(not(target_arch = "wasm32"), no_mangle)]
    unsafe extern "C" fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E1X2E0X00run() {
      $($path_to_types)*::_export_run_cabi::<$ty>()
    }
    #[cfg_attr(target_arch = "wasm32", export_name = "register")]
    #[cfg_attr(not(target_arch = "wasm32"), no_mangle)]
    unsafe extern "C" fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E1X2E0X00register(arg0: *mut u8,arg1: *mut u8,arg2: *mut u8,) {
      $($path_to_types)*::_export_register_cabi::<$ty>(arg0, arg1, arg2)
    }
    #[cfg_attr(not(target_arch = "wasm32"), no_mangle)]
    unsafe extern "C" fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E1X2E0X00X5Bresource_dropX5Dcallback_function(arg0: usize) {
      $($path_to_types)*::_export_drop_callbackFunction_cabi::<<$ty as $($path_to_types)*::Guest>::CallbackFunction>(arg0)
    }

    #[cfg_attr(not(target_arch = "wasm32"), no_mangle)]
    unsafe extern "C" fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E1X2E0X00X5Bresource_dropX5Dcallback_data(arg0: usize) {
      $($path_to_types)*::_export_drop_callbackData_cabi::<<$ty as $($path_to_types)*::Guest>::CallbackData>(arg0)
    }

    #[cfg_attr(not(target_arch = "wasm32"), no_mangle)]
    unsafe extern "C" fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E1X2E0X00X5Bresource_dropX5Devent_subscription(arg0: usize) {
      $($path_to_types)*::_export_drop_eventSubscription_cabi::<<$ty as $($path_to_types)*::Guest>::EventSubscription>(arg0)
    }

    #[cfg_attr(not(target_arch = "wasm32"), no_mangle)]
    unsafe extern "C" fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E1X2E0X00X5Bresource_dropX5Devent_generator(arg0: usize) {
      $($path_to_types)*::_export_drop_eventGenerator_cabi::<<$ty as $($path_to_types)*::Guest>::EventGenerator>(arg0)
    }

  };);
}
                #[doc(hidden)]
                pub(crate) use __export_symmetric_runtime_symmetric_executor_0_1_0_cabi;
            }
        }
    }
}
mod _rt {
    #![allow(dead_code, clippy::all)]

    use core::fmt;
    use core::marker;
    use core::sync::atomic::{AtomicUsize, Ordering::Relaxed};

    /// A type which represents a component model resource, either imported or
    /// exported into this component.
    ///
    /// This is a low-level wrapper which handles the lifetime of the resource
    /// (namely this has a destructor). The `T` provided defines the component model
    /// intrinsics that this wrapper uses.
    ///
    /// One of the chief purposes of this type is to provide `Deref` implementations
    /// to access the underlying data when it is owned.
    ///
    /// This type is primarily used in generated code for exported and imported
    /// resources.
    #[repr(transparent)]
    pub struct Resource<T: WasmResource> {
        // NB: This would ideally be `usize` but it is not. The fact that this has
        // interior mutability is not exposed in the API of this type except for the
        // `take_handle` method which is supposed to in theory be private.
        //
        // This represents, almost all the time, a valid handle value. When it's
        // invalid it's stored as `0`.
        handle: AtomicUsize,
        _marker: marker::PhantomData<T>,
    }

    /// A trait which all wasm resources implement, namely providing the ability to
    /// drop a resource.
    ///
    /// This generally is implemented by generated code, not user-facing code.
    #[allow(clippy::missing_safety_doc)]
    pub unsafe trait WasmResource {
        /// Invokes the `[resource-drop]...` intrinsic.
        unsafe fn drop(handle: usize);
    }

    impl<T: WasmResource> Resource<T> {
        #[doc(hidden)]
        pub unsafe fn from_handle(handle: usize) -> Self {
            debug_assert!(handle != 0);
            Self {
                handle: AtomicUsize::new(handle),
                _marker: marker::PhantomData,
            }
        }

        /// Takes ownership of the handle owned by `resource`.
        ///
        /// Note that this ideally would be `into_handle` taking `Resource<T>` by
        /// ownership. The code generator does not enable that in all situations,
        /// unfortunately, so this is provided instead.
        ///
        /// Also note that `take_handle` is in theory only ever called on values
        /// owned by a generated function. For example a generated function might
        /// take `Resource<T>` as an argument but then call `take_handle` on a
        /// reference to that argument. In that sense the dynamic nature of
        /// `take_handle` should only be exposed internally to generated code, not
        /// to user code.
        #[doc(hidden)]
        pub fn take_handle(resource: &Resource<T>) -> usize {
            resource.handle.swap(0, Relaxed)
        }

        #[doc(hidden)]
        pub fn handle(resource: &Resource<T>) -> usize {
            resource.handle.load(Relaxed)
        }
    }

    impl<T: WasmResource> fmt::Debug for Resource<T> {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
            f.debug_struct("Resource")
                .field("handle", &self.handle)
                .finish()
        }
    }

    impl<T: WasmResource> Drop for Resource<T> {
        fn drop(&mut self) {
            unsafe {
                match self.handle.load(Relaxed) {
                    // If this handle was "taken" then don't do anything in the
                    // destructor.
                    0 => {}

                    // ... but otherwise do actually destroy it with the imported
                    // component model intrinsic as defined through `T`.
                    other => T::drop(other),
                }
            }
        }
    }
    pub use alloc_crate::boxed::Box;

    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen::rt::run_ctors_once();
    }
    #[cfg(feature = "never")]
    pub mod stream_and_future_support {
        use {
            futures::{
                channel::oneshot,
                future::{self, FutureExt},
                sink::Sink,
                stream::Stream,
            },
            std::{
                collections::hash_map::Entry,
                convert::Infallible,
                fmt,
                future::{Future, IntoFuture},
                iter,
                marker::PhantomData,
                mem::{self, ManuallyDrop, MaybeUninit},
                pin::Pin,
                task::{Context, Poll},
            },
            wit_bindgen_rt::async_support::{self, Handle},
        };

        #[doc(hidden)]
        pub trait FuturePayload: Unpin + Sized + 'static {
            fn new() -> u32;
            async fn write(future: u32, value: Self) -> bool;
            async fn read(future: u32) -> Option<Self>;
            fn cancel_write(future: u32);
            fn cancel_read(future: u32);
            fn close_writable(future: u32);
            fn close_readable(future: u32);
        }

        /// Represents the writable end of a Component Model `future`.
        pub struct FutureWriter<T: FuturePayload> {
            handle: u32,
            _phantom: PhantomData<T>,
        }

        impl<T: FuturePayload> fmt::Debug for FutureWriter<T> {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                f.debug_struct("FutureWriter")
                    .field("handle", &self.handle)
                    .finish()
            }
        }

        /// Represents a write operation which may be canceled prior to completion.
        pub struct CancelableWrite<T: FuturePayload> {
            writer: Option<FutureWriter<T>>,
            future: Pin<Box<dyn Future<Output = ()>>>,
        }

        impl<T: FuturePayload> Future for CancelableWrite<T> {
            type Output = ();

            fn poll(self: Pin<&mut Self>, cx: &mut Context) -> Poll<()> {
                let me = self.get_mut();
                match me.future.poll_unpin(cx) {
                    Poll::Ready(()) => {
                        me.writer = None;
                        Poll::Ready(())
                    }
                    Poll::Pending => Poll::Pending,
                }
            }
        }

        impl<T: FuturePayload> CancelableWrite<T> {
            /// Cancel this write if it hasn't already completed, returning the original `FutureWriter`.
            ///
            /// This method will panic if the write has already completed.
            pub fn cancel(mut self) -> FutureWriter<T> {
                self.cancel_mut()
            }

            fn cancel_mut(&mut self) -> FutureWriter<T> {
                let writer = self.writer.take().unwrap();
                async_support::with_entry(writer.handle, |entry| match entry {
                    Entry::Vacant(_) => unreachable!(),
                    Entry::Occupied(mut entry) => match entry.get() {
                        Handle::LocalOpen
                        | Handle::LocalWaiting(_)
                        | Handle::Read
                        | Handle::LocalClosed => unreachable!(),
                        Handle::LocalReady(..) => {
                            entry.insert(Handle::LocalOpen);
                        }
                        Handle::Write => T::cancel_write(writer.handle),
                    },
                });
                writer
            }
        }

        impl<T: FuturePayload> Drop for CancelableWrite<T> {
            fn drop(&mut self) {
                if self.writer.is_some() {
                    self.cancel_mut();
                }
            }
        }

        impl<T: FuturePayload> FutureWriter<T> {
            /// Write the specified value to this `future`.
            pub fn write(self, v: T) -> CancelableWrite<T> {
                let handle = self.handle;
                CancelableWrite {
                    writer: Some(self),
                    future: async_support::with_entry(handle, |entry| match entry {
                        Entry::Vacant(_) => unreachable!(),
                        Entry::Occupied(mut entry) => match entry.get() {
                            Handle::LocalOpen => {
                                let mut v = Some(v);
                                Box::pin(future::poll_fn(move |cx| {
                                    async_support::with_entry(handle, |entry| match entry {
                                        Entry::Vacant(_) => unreachable!(),
                                        Entry::Occupied(mut entry) => match entry.get() {
                                            Handle::LocalOpen => {
                                                entry.insert(Handle::LocalReady(
                                                    Box::new(v.take().unwrap()),
                                                    cx.waker().clone(),
                                                ));
                                                Poll::Pending
                                            }
                                            Handle::LocalReady(..) => Poll::Pending,
                                            Handle::LocalClosed => Poll::Ready(()),
                                            Handle::LocalWaiting(_)
                                            | Handle::Read
                                            | Handle::Write => {
                                                unreachable!()
                                            }
                                        },
                                    })
                                }))
                                    as Pin<Box<dyn Future<Output = _>>>
                            }
                            Handle::LocalWaiting(_) => {
                                let Handle::LocalWaiting(tx) = entry.insert(Handle::LocalClosed)
                                else {
                                    unreachable!()
                                };
                                _ = tx.send(Box::new(v));
                                Box::pin(future::ready(()))
                            }
                            Handle::LocalClosed => Box::pin(future::ready(())),
                            Handle::Read | Handle::LocalReady(..) => unreachable!(),
                            Handle::Write => Box::pin(T::write(handle, v).map(drop)),
                        },
                    }),
                }
            }
        }

        impl<T: FuturePayload> Drop for FutureWriter<T> {
            fn drop(&mut self) {
                async_support::with_entry(self.handle, |entry| match entry {
                    Entry::Vacant(_) => unreachable!(),
                    Entry::Occupied(mut entry) => match entry.get_mut() {
                        Handle::LocalOpen | Handle::LocalWaiting(_) | Handle::LocalReady(..) => {
                            entry.insert(Handle::LocalClosed);
                        }
                        Handle::Read => unreachable!(),
                        Handle::Write | Handle::LocalClosed => {
                            entry.remove();
                            T::close_writable(self.handle);
                        }
                    },
                });
            }
        }

        /// Represents a read operation which may be canceled prior to completion.
        pub struct CancelableRead<T: FuturePayload> {
            reader: Option<FutureReader<T>>,
            future: Pin<Box<dyn Future<Output = Option<T>>>>,
        }

        impl<T: FuturePayload> Future for CancelableRead<T> {
            type Output = Option<T>;

            fn poll(self: Pin<&mut Self>, cx: &mut Context) -> Poll<Option<T>> {
                let me = self.get_mut();
                match me.future.poll_unpin(cx) {
                    Poll::Ready(v) => {
                        me.reader = None;
                        Poll::Ready(v)
                    }
                    Poll::Pending => Poll::Pending,
                }
            }
        }

        impl<T: FuturePayload> CancelableRead<T> {
            /// Cancel this read if it hasn't already completed, returning the original `FutureReader`.
            ///
            /// This method will panic if the read has already completed.
            pub fn cancel(mut self) -> FutureReader<T> {
                self.cancel_mut()
            }

            fn cancel_mut(&mut self) -> FutureReader<T> {
                let reader = self.reader.take().unwrap();
                async_support::with_entry(reader.handle, |entry| match entry {
                    Entry::Vacant(_) => unreachable!(),
                    Entry::Occupied(mut entry) => match entry.get() {
                        Handle::LocalOpen
                        | Handle::LocalReady(..)
                        | Handle::Write
                        | Handle::LocalClosed => unreachable!(),
                        Handle::LocalWaiting(_) => {
                            entry.insert(Handle::LocalOpen);
                        }
                        Handle::Read => T::cancel_read(reader.handle),
                    },
                });
                reader
            }
        }

        impl<T: FuturePayload> Drop for CancelableRead<T> {
            fn drop(&mut self) {
                if self.reader.is_some() {
                    self.cancel_mut();
                }
            }
        }

        /// Represents the readable end of a Component Model `future`.
        pub struct FutureReader<T: FuturePayload> {
            handle: u32,
            _phantom: PhantomData<T>,
        }

        impl<T: FuturePayload> fmt::Debug for FutureReader<T> {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                f.debug_struct("FutureReader")
                    .field("handle", &self.handle)
                    .finish()
            }
        }

        impl<T: FuturePayload> FutureReader<T> {
            #[doc(hidden)]
            pub fn from_handle(handle: u32) -> Self {
                async_support::with_entry(handle, |entry| match entry {
                    Entry::Vacant(entry) => {
                        entry.insert(Handle::Read);
                    }
                    Entry::Occupied(mut entry) => match entry.get() {
                        Handle::Write => {
                            entry.insert(Handle::LocalOpen);
                        }
                        Handle::Read
                        | Handle::LocalOpen
                        | Handle::LocalReady(..)
                        | Handle::LocalWaiting(_)
                        | Handle::LocalClosed => {
                            unreachable!()
                        }
                    },
                });

                Self {
                    handle,
                    _phantom: PhantomData,
                }
            }

            #[doc(hidden)]
            pub fn into_handle(self) -> u32 {
                async_support::with_entry(self.handle, |entry| match entry {
                    Entry::Vacant(_) => unreachable!(),
                    Entry::Occupied(mut entry) => match entry.get() {
                        Handle::LocalOpen => {
                            entry.insert(Handle::Write);
                        }
                        Handle::Read | Handle::LocalClosed => {
                            entry.remove();
                        }
                        Handle::LocalReady(..) | Handle::LocalWaiting(_) | Handle::Write => {
                            unreachable!()
                        }
                    },
                });

                ManuallyDrop::new(self).handle
            }
        }

        impl<T: FuturePayload> IntoFuture for FutureReader<T> {
            type Output = Option<T>;
            type IntoFuture = CancelableRead<T>;

            /// Convert this object into a `Future` which will resolve when a value is
            /// written to the writable end of this `future` (yielding a `Some` result)
            /// or when the writable end is dropped (yielding a `None` result).
            fn into_future(self) -> Self::IntoFuture {
                let handle = self.handle;
                CancelableRead {
                    reader: Some(self),
                    future: async_support::with_entry(handle, |entry| match entry {
                        Entry::Vacant(_) => unreachable!(),
                        Entry::Occupied(mut entry) => match entry.get() {
                            Handle::Write | Handle::LocalWaiting(_) => unreachable!(),
                            Handle::Read => Box::pin(async move { T::read(handle).await })
                                as Pin<Box<dyn Future<Output = _>>>,
                            Handle::LocalOpen => {
                                let (tx, rx) = oneshot::channel();
                                entry.insert(Handle::LocalWaiting(tx));
                                Box::pin(
                                    async move { rx.await.ok().map(|v| *v.downcast().unwrap()) },
                                )
                            }
                            Handle::LocalClosed => Box::pin(future::ready(None)),
                            Handle::LocalReady(..) => {
                                let Handle::LocalReady(v, waker) =
                                    entry.insert(Handle::LocalClosed)
                                else {
                                    unreachable!()
                                };
                                waker.wake();
                                Box::pin(future::ready(Some(*v.downcast().unwrap())))
                            }
                        },
                    }),
                }
            }
        }

        impl<T: FuturePayload> Drop for FutureReader<T> {
            fn drop(&mut self) {
                async_support::with_entry(self.handle, |entry| match entry {
                    Entry::Vacant(_) => unreachable!(),
                    Entry::Occupied(mut entry) => match entry.get_mut() {
                        Handle::LocalReady(..) => {
                            let Handle::LocalReady(_, waker) = entry.insert(Handle::LocalClosed)
                            else {
                                unreachable!()
                            };
                            waker.wake();
                        }
                        Handle::LocalOpen | Handle::LocalWaiting(_) => {
                            entry.insert(Handle::LocalClosed);
                        }
                        Handle::Read | Handle::LocalClosed => {
                            entry.remove();
                            T::close_readable(self.handle);
                        }
                        Handle::Write => unreachable!(),
                    },
                });
            }
        }

        #[doc(hidden)]
        pub trait StreamPayload: Unpin + Sized + 'static {
            fn new() -> u32;
            async fn write(stream: u32, values: &[Self]) -> Option<usize>;
            async fn read(stream: u32, values: &mut [MaybeUninit<Self>]) -> Option<usize>;
            fn cancel_write(stream: u32);
            fn cancel_read(stream: u32);
            fn close_writable(stream: u32);
            fn close_readable(stream: u32);
        }

        struct CancelWriteOnDrop<T: StreamPayload> {
            handle: Option<u32>,
            _phantom: PhantomData<T>,
        }

        impl<T: StreamPayload> Drop for CancelWriteOnDrop<T> {
            fn drop(&mut self) {
                if let Some(handle) = self.handle.take() {
                    async_support::with_entry(handle, |entry| match entry {
                        Entry::Vacant(_) => unreachable!(),
                        Entry::Occupied(mut entry) => match entry.get() {
                            Handle::LocalOpen
                            | Handle::LocalWaiting(_)
                            | Handle::Read
                            | Handle::LocalClosed => unreachable!(),
                            Handle::LocalReady(..) => {
                                entry.insert(Handle::LocalOpen);
                            }
                            Handle::Write => T::cancel_write(handle),
                        },
                    });
                }
            }
        }

        /// Represents the writable end of a Component Model `stream`.
        pub struct StreamWriter<T: StreamPayload> {
            handle: u32,
            future: Option<Pin<Box<dyn Future<Output = ()> + 'static>>>,
            _phantom: PhantomData<T>,
        }

        impl<T: StreamPayload> StreamWriter<T> {
            /// Cancel the current pending write operation.
            ///
            /// This will panic if no such operation is pending.
            pub fn cancel(&mut self) {
                assert!(self.future.is_some());
                self.future = None;
            }
        }

        impl<T: StreamPayload> fmt::Debug for StreamWriter<T> {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                f.debug_struct("StreamWriter")
                    .field("handle", &self.handle)
                    .finish()
            }
        }

        impl<T: StreamPayload> Sink<Vec<T>> for StreamWriter<T> {
            type Error = Infallible;

            fn poll_ready(self: Pin<&mut Self>, cx: &mut Context) -> Poll<Result<(), Self::Error>> {
                let me = self.get_mut();

                if let Some(future) = &mut me.future {
                    match future.as_mut().poll(cx) {
                        Poll::Ready(_) => {
                            me.future = None;
                            Poll::Ready(Ok(()))
                        }
                        Poll::Pending => Poll::Pending,
                    }
                } else {
                    Poll::Ready(Ok(()))
                }
            }

            fn start_send(self: Pin<&mut Self>, item: Vec<T>) -> Result<(), Self::Error> {
                assert!(self.future.is_none());
                async_support::with_entry(self.handle, |entry| match entry {
                    Entry::Vacant(_) => unreachable!(),
                    Entry::Occupied(mut entry) => match entry.get() {
                        Handle::LocalOpen => {
                            let handle = self.handle;
                            let mut item = Some(item);
                            let mut cancel_on_drop = Some(CancelWriteOnDrop::<T> {
                                handle: Some(handle),
                                _phantom: PhantomData,
                            });
                            self.get_mut().future = Some(Box::pin(future::poll_fn(move |cx| {
                                async_support::with_entry(handle, |entry| match entry {
                                    Entry::Vacant(_) => unreachable!(),
                                    Entry::Occupied(mut entry) => match entry.get() {
                                        Handle::LocalOpen => {
                                            if let Some(item) = item.take() {
                                                entry.insert(Handle::LocalReady(
                                                    Box::new(item),
                                                    cx.waker().clone(),
                                                ));
                                                Poll::Pending
                                            } else {
                                                cancel_on_drop.take().unwrap().handle = None;
                                                Poll::Ready(())
                                            }
                                        }
                                        Handle::LocalReady(..) => Poll::Pending,
                                        Handle::LocalClosed => {
                                            cancel_on_drop.take().unwrap().handle = None;
                                            Poll::Ready(())
                                        }
                                        Handle::LocalWaiting(_) | Handle::Read | Handle::Write => {
                                            unreachable!()
                                        }
                                    },
                                })
                            })));
                        }
                        Handle::LocalWaiting(_) => {
                            let Handle::LocalWaiting(tx) = entry.insert(Handle::LocalOpen) else {
                                unreachable!()
                            };
                            _ = tx.send(Box::new(item));
                        }
                        Handle::LocalClosed => (),
                        Handle::Read | Handle::LocalReady(..) => unreachable!(),
                        Handle::Write => {
                            let handle = self.handle;
                            let mut cancel_on_drop = CancelWriteOnDrop::<T> {
                                handle: Some(handle),
                                _phantom: PhantomData,
                            };
                            self.get_mut().future = Some(Box::pin(async move {
                                let mut offset = 0;
                                while offset < item.len() {
                                    if let Some(count) = T::write(handle, &item[offset..]).await {
                                        offset += count;
                                    } else {
                                        break;
                                    }
                                }
                                cancel_on_drop.handle = None;
                                drop(cancel_on_drop);
                            }));
                        }
                    },
                });
                Ok(())
            }

            fn poll_flush(self: Pin<&mut Self>, cx: &mut Context) -> Poll<Result<(), Self::Error>> {
                self.poll_ready(cx)
            }

            fn poll_close(self: Pin<&mut Self>, cx: &mut Context) -> Poll<Result<(), Self::Error>> {
                self.poll_ready(cx)
            }
        }

        impl<T: StreamPayload> Drop for StreamWriter<T> {
            fn drop(&mut self) {
                self.future = None;

                async_support::with_entry(self.handle, |entry| match entry {
                    Entry::Vacant(_) => unreachable!(),
                    Entry::Occupied(mut entry) => match entry.get_mut() {
                        Handle::LocalOpen | Handle::LocalWaiting(_) | Handle::LocalReady(..) => {
                            entry.insert(Handle::LocalClosed);
                        }
                        Handle::Read => unreachable!(),
                        Handle::Write | Handle::LocalClosed => {
                            entry.remove();
                            T::close_writable(self.handle);
                        }
                    },
                });
            }
        }

        struct CancelReadOnDrop<T: StreamPayload> {
            handle: Option<u32>,
            _phantom: PhantomData<T>,
        }

        impl<T: StreamPayload> Drop for CancelReadOnDrop<T> {
            fn drop(&mut self) {
                if let Some(handle) = self.handle.take() {
                    async_support::with_entry(handle, |entry| match entry {
                        Entry::Vacant(_) => unreachable!(),
                        Entry::Occupied(mut entry) => match entry.get() {
                            Handle::LocalOpen
                            | Handle::LocalReady(..)
                            | Handle::Write
                            | Handle::LocalClosed => unreachable!(),
                            Handle::LocalWaiting(_) => {
                                entry.insert(Handle::LocalOpen);
                            }
                            Handle::Read => T::cancel_read(handle),
                        },
                    });
                }
            }
        }

        /// Represents the readable end of a Component Model `stream`.
        pub struct StreamReader<T: StreamPayload> {
            handle: u32,
            future: Option<Pin<Box<dyn Future<Output = Option<Vec<T>>> + 'static>>>,
            _phantom: PhantomData<T>,
        }

        impl<T: StreamPayload> StreamReader<T> {
            /// Cancel the current pending read operation.
            ///
            /// This will panic if no such operation is pending.
            pub fn cancel(&mut self) {
                assert!(self.future.is_some());
                self.future = None;
            }
        }

        impl<T: StreamPayload> fmt::Debug for StreamReader<T> {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                f.debug_struct("StreamReader")
                    .field("handle", &self.handle)
                    .finish()
            }
        }

        impl<T: StreamPayload> StreamReader<T> {
            #[doc(hidden)]
            pub fn from_handle(handle: u32) -> Self {
                async_support::with_entry(handle, |entry| match entry {
                    Entry::Vacant(entry) => {
                        entry.insert(Handle::Read);
                    }
                    Entry::Occupied(mut entry) => match entry.get() {
                        Handle::Write => {
                            entry.insert(Handle::LocalOpen);
                        }
                        Handle::Read
                        | Handle::LocalOpen
                        | Handle::LocalReady(..)
                        | Handle::LocalWaiting(_)
                        | Handle::LocalClosed => {
                            unreachable!()
                        }
                    },
                });

                Self {
                    handle,
                    future: None,
                    _phantom: PhantomData,
                }
            }

            #[doc(hidden)]
            pub fn into_handle(self) -> u32 {
                async_support::with_entry(self.handle, |entry| match entry {
                    Entry::Vacant(_) => unreachable!(),
                    Entry::Occupied(mut entry) => match entry.get() {
                        Handle::LocalOpen => {
                            entry.insert(Handle::Write);
                        }
                        Handle::Read | Handle::LocalClosed => {
                            entry.remove();
                        }
                        Handle::LocalReady(..) | Handle::LocalWaiting(_) | Handle::Write => {
                            unreachable!()
                        }
                    },
                });

                ManuallyDrop::new(self).handle
            }
        }

        impl<T: StreamPayload> Stream for StreamReader<T> {
            type Item = Vec<T>;

            fn poll_next(self: Pin<&mut Self>, cx: &mut Context) -> Poll<Option<Self::Item>> {
                let me = self.get_mut();

                if me.future.is_none() {
                    me.future = Some(async_support::with_entry(me.handle, |entry| match entry {
                        Entry::Vacant(_) => unreachable!(),
                        Entry::Occupied(mut entry) => match entry.get() {
                            Handle::Write | Handle::LocalWaiting(_) => unreachable!(),
                            Handle::Read => {
                                let handle = me.handle;
                                let mut cancel_on_drop = CancelReadOnDrop::<T> {
                                    handle: Some(handle),
                                    _phantom: PhantomData,
                                };
                                Box::pin(async move {
                                    let mut buffer = iter::repeat_with(MaybeUninit::uninit)
                                        .take(ceiling(64 * 1024, mem::size_of::<T>()))
                                        .collect::<Vec<_>>();

                                    let result = if let Some(count) =
                                        T::read(handle, &mut buffer).await
                                    {
                                        buffer.truncate(count);
                                        Some(unsafe {
                                            mem::transmute::<Vec<MaybeUninit<T>>, Vec<T>>(buffer)
                                        })
                                    } else {
                                        None
                                    };
                                    cancel_on_drop.handle = None;
                                    drop(cancel_on_drop);
                                    result
                                })
                                    as Pin<Box<dyn Future<Output = _>>>
                            }
                            Handle::LocalOpen => {
                                let (tx, rx) = oneshot::channel();
                                entry.insert(Handle::LocalWaiting(tx));
                                let mut cancel_on_drop = CancelReadOnDrop::<T> {
                                    handle: Some(me.handle),
                                    _phantom: PhantomData,
                                };
                                Box::pin(async move {
                                    let result =
                                        rx.map(|v| v.ok().map(|v| *v.downcast().unwrap())).await;
                                    cancel_on_drop.handle = None;
                                    drop(cancel_on_drop);
                                    result
                                })
                            }
                            Handle::LocalClosed => Box::pin(future::ready(None)),
                            Handle::LocalReady(..) => {
                                let Handle::LocalReady(v, waker) = entry.insert(Handle::LocalOpen)
                                else {
                                    unreachable!()
                                };
                                waker.wake();
                                Box::pin(future::ready(Some(*v.downcast().unwrap())))
                            }
                        },
                    }));
                }

                match me.future.as_mut().unwrap().as_mut().poll(cx) {
                    Poll::Ready(v) => {
                        me.future = None;
                        Poll::Ready(v)
                    }
                    Poll::Pending => Poll::Pending,
                }
            }
        }

        impl<T: StreamPayload> Drop for StreamReader<T> {
            fn drop(&mut self) {
                self.future = None;

                async_support::with_entry(self.handle, |entry| match entry {
                    Entry::Vacant(_) => unreachable!(),
                    Entry::Occupied(mut entry) => match entry.get_mut() {
                        Handle::LocalReady(..) => {
                            let Handle::LocalReady(_, waker) = entry.insert(Handle::LocalClosed)
                            else {
                                unreachable!()
                            };
                            waker.wake();
                        }
                        Handle::LocalOpen | Handle::LocalWaiting(_) => {
                            entry.insert(Handle::LocalClosed);
                        }
                        Handle::Read | Handle::LocalClosed => {
                            entry.remove();
                            T::close_readable(self.handle);
                        }
                        Handle::Write => unreachable!(),
                    },
                });
            }
        }

        /// Creates a new Component Model `future` with the specified payload type.
        pub fn new_future<T: FuturePayload>() -> (FutureWriter<T>, FutureReader<T>) {
            let handle = T::new();
            async_support::with_entry(handle, |entry| match entry {
                Entry::Vacant(entry) => {
                    entry.insert(Handle::LocalOpen);
                }
                Entry::Occupied(_) => unreachable!(),
            });
            (
                FutureWriter {
                    handle,
                    _phantom: PhantomData,
                },
                FutureReader {
                    handle,
                    _phantom: PhantomData,
                },
            )
        }

        /// Creates a new Component Model `stream` with the specified payload type.
        pub fn new_stream<T: StreamPayload>() -> (StreamWriter<T>, StreamReader<T>) {
            let handle = T::new();
            async_support::with_entry(handle, |entry| match entry {
                Entry::Vacant(entry) => {
                    entry.insert(Handle::LocalOpen);
                }
                Entry::Occupied(_) => unreachable!(),
            });
            (
                StreamWriter {
                    handle,
                    future: None,
                    _phantom: PhantomData,
                },
                StreamReader {
                    handle,
                    future: None,
                    _phantom: PhantomData,
                },
            )
        }

        fn ceiling(x: usize, y: usize) -> usize {
            (x / y) + if x % y == 0 { 0 } else { 1 }
        }
    }
    extern crate alloc as alloc_crate;
}
#[allow(unused_imports)]
// pub use _rt::stream_and_future_support;

/// Generates `#[no_mangle]` functions to export the specified type as the
/// root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]

macro_rules! __export_executor_impl {
  ($ty:ident) => (self::export!($ty with_types_in self););
  ($ty:ident with_types_in $($path_to_types_root:tt)*) => (
  $($path_to_types_root)*::exports::symmetric::runtime::symmetric_executor::__export_symmetric_runtime_symmetric_executor_0_1_0_cabi!($ty with_types_in $($path_to_types_root)*::exports::symmetric::runtime::symmetric_executor);
  )
}
#[doc(inline)]
pub(crate) use __export_executor_impl as export;

#[cfg(target_arch = "wasm32")]
#[link_section = "component-type:wit-bindgen:0.36.0:symmetric:runtime@0.1.0:executor:encoded world"]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 793] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x9a\x05\x01A\x02\x01\
A\x02\x01B\x20\x04\0\x11callback-function\x03\x01\x04\0\x0dcallback-data\x03\x01\
\x04\0\x12event-subscription\x03\x01\x04\0\x0fevent-generator\x03\x01\x01m\x02\x07\
started\x0bnot-started\x04\0\x0bcall-status\x03\0\x04\x01m\x02\x07pending\x05rea\
dy\x04\0\x0ecallback-state\x03\0\x06\x01h\x02\x01@\x01\x04self\x08\0\x7f\x04\0\x20\
[method]event-subscription.ready\x01\x09\x01i\x02\x01@\x01\x0bnanosecondsw\0\x0a\
\x04\0'[static]event-subscription.from-timeout\x01\x0b\x01@\x01\x04self\x08\0\x0a\
\x04\0\x1e[method]event-subscription.dup\x01\x0c\x01@\x01\x04self\x08\x01\0\x04\0\
\x20[method]event-subscription.reset\x01\x0d\x01i\x03\x01@\0\0\x0e\x04\0\x1c[con\
structor]event-generator\x01\x0f\x01h\x03\x01@\x01\x04self\x10\0\x0a\x04\0![meth\
od]event-generator.subscribe\x01\x11\x01@\x01\x04self\x10\x01\0\x04\0\x20[method\
]event-generator.activate\x01\x12\x01@\0\x01\0\x04\0\x03run\x01\x13\x01i\0\x01i\x01\
\x01@\x03\x07trigger\x0a\x08callback\x14\x04data\x15\x01\0\x04\0\x08register\x01\
\x16\x04\0*symmetric:runtime/symmetric-executor@0.1.0\x05\0\x04\0\x20symmetric:r\
untime/executor@0.1.0\x04\0\x0b\x0e\x01\0\x08executor\x03\0\0\0G\x09producers\x01\
\x0cprocessed-by\x02\x0dwit-component\x070.221.2\x10wit-bindgen-rust\x060.36.0";

#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen::rt::maybe_link_cabi_realloc();
}
