package symmetric:runtime@0.1.0;

world executor {
    export symmetric-executor;
}

world stream-impl {
    export symmetric-stream;
}

world module {
    import symmetric-executor;
    import symmetric-stream;
}
