// This file is generated by ./ci/rebuild-libwit-bindgen-cabi.sh

unsafe extern "C" {
    #[link_name = "wit_bindgen_0_61_1_get_task_context"]
    pub fn get() -> *mut u8;
    #[link_name = "wit_bindgen_0_61_1_set_task_context"]
    pub fn set(ptr: *mut u8);
}
