package my:strings;

world runner {
  import cat: interface {
    type my-string = string;
    foo: func(x: my-string);
    bar: func() -> my-string;
  }
}

world test {
  export cat: interface {
    type my-string = string;
    foo: func(x: my-string);
    bar: func() -> my-string;
  }
}
