name: 'Install the wasi-sdk'
description: 'Install the wasi-sdk toolchain'

runs:
  using: composite
  steps:
    - run: |
        curl --retry 5 --retry-all-errors -L -o wasi-sdk.tar.gz https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-29/wasi-sdk-29.0-x86_64-linux.tar.gz
        tar xzvf wasi-sdk.tar.gz
        echo "WASI_SDK_PATH=`pwd`/wasi-sdk-29.0-x86_64-linux" >> $GITHUB_ENV
      if: runner.os == 'Linux'
      shell: bash
      working-directory: ${{ runner.tool_cache }}
    - run: |
        curl --retry 5 --retry-all-errors -L -o wasi-sdk.tar.gz https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-29/wasi-sdk-29.0-arm64-macos.tar.gz
        tar xzvf wasi-sdk.tar.gz
        echo "WASI_SDK_PATH=`pwd`/wasi-sdk-29.0-arm64-macos" >> $GITHUB_ENV
      if: runner.os == 'macOS'
      shell: bash
      working-directory: ${{ runner.tool_cache }}
    - run: |
        curl --retry 5 --retry-all-errors -L -o wasi-sdk.tar.gz https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-29/wasi-sdk-29.0-x86_64-windows.tar.gz
        tar xzvf wasi-sdk.tar.gz
        echo "WASI_SDK_PATH=`pwd`/wasi-sdk-29.0-x86_64-windows" >> $GITHUB_ENV
      if: runner.os == 'Windows'
      shell: bash
      working-directory: ${{ runner.tool_cache }}

    - name: Setup `wasm-tools`
      uses: bytecodealliance/actions/wasm-tools/setup@v1
      with:
        version: "1.241.2"
    - name: Setup `wasmtime`
      uses: bytecodealliance/actions/wasmtime/setup@v1
      with:
        version: "dev"
