name: 'Install the wasi-sdk'
description: 'Install the wasi-sdk toolchain'

runs:
  using: composite
  steps:
    - run: |
        curl https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-25/wasi-sdk-25.0-x86_64-linux.tar.gz -L | tar xzvf -
        echo "WASI_SDK_PATH=`pwd`/wasi-sdk-25.0-x86_64-linux" >> $GITHUB_ENV
      if: runner.os == 'Linux'
      shell: bash
    - run: |
        curl https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-25/wasi-sdk-25.0-x86_64-macos.tar.gz -L | tar xzvf -
        echo "WASI_SDK_PATH=`pwd`/wasi-sdk-25.0-x86_64-macos" >> $GITHUB_ENV
      if: runner.os == 'macOS'
      shell: bash
    - run: |
        curl https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-25/wasi-sdk-25.0-x86_64-windows.tar.gz -L | tar xzvf -
        echo "WASI_SDK_PATH=`pwd`/wasi-sdk-25.0-x86_64-windows" >> $GITHUB_ENV
      if: runner.os == 'Windows'
      shell: bash
    - name: Setup `wasm-tools`
      uses: bytecodealliance/actions/wasm-tools/setup@v1
      with:
        version: "1.215.0"
    - name: Setup `wasmtime`
      uses: bytecodealliance/actions/wasmtime/setup@v1
      with:
        version: "30.0.1"
