// Generated by `wit-bindgen` 0.3.0. DO NOT EDIT!
#ifndef __CPP_NATIVE_BINDINGS_THE_WORLD_H
#define __CPP_NATIVE_BINDINGS_THE_WORLD_H
#define WIT_HOST_DIRECT
#include <cassert>
#include <cstdint>
#include <map>
#include <utility>
#include <wit-host.h>
namespace foo {
namespace foo {
namespace resources {
class R : public wit::ResourceImportBase {

public:
  ~R();
  R(uint32_t a);
  void Add(uint32_t b);
  R(wit::ResourceImportBase &&);

  R(R &&) = default;
};

R Create();
void Borrows(std::reference_wrapper<const R> o);
void Consume(R o);
// export_interface Interface(Id { idx: 0 })
} // namespace resources
} // namespace foo
} // namespace foo
#include "exports-foo-foo-resources-R.h"
namespace exports {
namespace foo {
namespace foo {
namespace resources {
R Create();
void Borrows(std::reference_wrapper<const R> o);
void Consume(R o);
} // namespace resources
} // namespace foo
} // namespace foo
} // namespace exports

#endif
