wit-version "0xa"

interface imports {
  take-basic: func(s: string)
  return-unicode: func() -> string
}

interface exports {
  test-imports: func()

  roundtrip: func(s: string) -> string
}

world strings {
  import imports: imports
  default export exports
}
