interface imports {
  take-basic: func(s: string)
  return-unicode: func() -> string
}

default world strings {
  import imports: self.imports

  export test-imports: func()
  export return-empty: func() -> string
  export roundtrip: func(s: string) -> string
}
