//@ dependencies = ['middle', 'leaf']
//@ wac = 'compose.wac'

package test:common;

interface test-types {
    flags f1 { a, b }
    record r1 { a: u8, b: f1 }
}

interface to-test {
    use test-types.{f1, r1};

    wrap: func(flag: f1) -> r1;
}

world leaf {
    export to-test;
}

world middle {
    import to-test;
    export to-test;
}

world runner {
    import to-test;
}
