// Generated by `wit-bindgen` 0.3.0. DO NOT EDIT!
#ifndef __CPP_GUEST_BINDINGS_ASYNC_MODULE_H
#define __CPP_GUEST_BINDINGS_ASYNC_MODULE_H
#define WIT_SYMMETRIC
#include <cstdint>
#include <utility>
#include <string_view>
#include <wit-guest.h>
#include <future>
namespace test {namespace test {namespace wait {std::future<void> Sleep(uint64_t nanoseconds);
// export_interface Interface(Id { idx: 0 })
}}}
namespace exports {namespace test {namespace test {namespace string_delay {std::future<wit::string> Forward(std::string_view s);
}}}}

#endif
