package test:xcrate;

interface a-imports {
  a: func();

  resource x {
    constructor();
    foo: func();
  }
}

world a {
  import a-imports;

  export a-unused: func();

  export an-unused-interface: interface {
    resource x {
      constructor();
      foo: func();
    }
  }
}

interface b-imports {
  b: func();

  resource x {
    constructor();
    foo: func();
  }
}

interface b-types {
  enum b-enum {
    b,
    bb,
    bbb,
  }
}

world b {
  import b-imports;

  use b-types.{b-enum};
  export b: func(e: b-enum);

  export an-exported-interface: interface {
    resource x {
      constructor();
      foo: func();
    }
  }
}

world c {
  import a-imports;
  include b;
}
