// Generated by `wit-bindgen` 0.42.1. DO NOT EDIT!
// Options used:
#[allow(dead_code, clippy::all)]
pub mod exports {
  pub mod wha {
    pub mod hoo {

      #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
      pub mod iii {
        #[used]
        #[doc(hidden)]
        static __FORCE_SECTION_REF: fn() =
        super::super::super::super::__link_custom_section_describing_imports;
        
        use super::super::super::super::_rt;

        #[derive(Debug)]
        #[repr(transparent)]
        pub struct Rrr{
          handle: _rt::Resource<Rrr>,
        }

        type _RrrRep<T> = Option<T>;

        impl Rrr{
          /// Creates a new resource from the specified representation.
          ///
          /// This function will create a new resource handle by moving `val` onto
          /// the heap and then passing that heap pointer to the component model to
          /// create a handle. The owned handle is then returned as `Rrr`.
          pub fn new<T: GuestRrr>(val: T) -> Self {
            Self::type_guard::<T>();
            let val: _RrrRep<T> = Some(val);
            let ptr: *mut _RrrRep<T> =
            _rt::Box::into_raw(_rt::Box::new(val));
            unsafe {
              Self::from_handle(T::_resource_new(ptr.cast()))
            }
          }

          /// Gets access to the underlying `T` which represents this resource.
          pub fn get<T: GuestRrr>(&self) -> &T {
            let ptr = unsafe { &*self.as_ptr::<T>() };
            ptr.as_ref().unwrap()
          }

          /// Gets mutable access to the underlying `T` which represents this
          /// resource.
          pub fn get_mut<T: GuestRrr>(&mut self) -> &mut T {
            let ptr = unsafe { &mut *self.as_ptr::<T>() };
            ptr.as_mut().unwrap()
          }

          /// Consumes this resource and returns the underlying `T`.
          pub fn into_inner<T: GuestRrr>(self) -> T {
            let ptr = unsafe { &mut *self.as_ptr::<T>() };
            ptr.take().unwrap()
          }

          #[doc(hidden)]
          pub unsafe fn from_handle(handle: u32) -> Self {
            Self {
              handle: unsafe { _rt::Resource::from_handle(handle) },
            }
          }

          #[doc(hidden)]
          pub fn take_handle(&self) -> u32 {
            _rt::Resource::take_handle(&self.handle)
          }

          #[doc(hidden)]
          pub fn handle(&self) -> u32 {
            _rt::Resource::handle(&self.handle)
          }

          // It's theoretically possible to implement the `GuestRrr` trait twice
          // so guard against using it with two different types here.
          #[doc(hidden)]
          fn type_guard<T: 'static>() {
            use core::any::TypeId;
            static mut LAST_TYPE: Option<TypeId> = None;
            unsafe {
              assert!(!cfg!(target_feature = "atomics"));
              let id = TypeId::of::<T>();
              match LAST_TYPE {
                Some(ty) => assert!(ty == id, "cannot use two types with this resource type"),
                None => LAST_TYPE = Some(id),
              }
            }
          }

          #[doc(hidden)]
          pub unsafe fn dtor<T: 'static>(handle: *mut u8) {
            Self::type_guard::<T>();
            let _ = unsafe { _rt::Box::from_raw(handle as *mut _RrrRep<T>) };
          }

          fn as_ptr<T: GuestRrr>(&self) -> *mut _RrrRep<T> {
            Rrr::type_guard::<T>();
            T::_resource_rep(self.handle()).cast()
          }
        }

        /// A borrowed version of [`Rrr`] which represents a borrowed value
        /// with the lifetime `'a`.
        #[derive(Debug)]
        #[repr(transparent)]
        pub struct RrrBorrow<'a> {
          rep: *mut u8,
          _marker: core::marker::PhantomData<&'a Rrr>,
        }

        impl<'a> RrrBorrow<'a>{
          #[doc(hidden)]
          pub unsafe fn lift(rep: usize) -> Self {
            Self {
              rep: rep as *mut u8,
              _marker: core::marker::PhantomData,
            }
          }

          /// Gets access to the underlying `T` in this resource.
          pub fn get<T: GuestRrr>(&self) -> &T {
            let ptr = unsafe { &mut *self.as_ptr::<T>() };
            ptr.as_ref().unwrap()
          }

          // NB: mutable access is not allowed due to the component model allowing
          // multiple borrows of the same resource.

          fn as_ptr<T: 'static>(&self) -> *mut _RrrRep<T> {
            Rrr::type_guard::<T>();
            self.rep.cast()
          }
        }
        

        unsafe impl _rt::WasmResource for Rrr{
          #[inline]
          unsafe fn drop(_handle: u32) {
            
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "[export]wha:hoo/iii")]
            unsafe extern "C" {
              #[link_name = "[resource-drop]rrr"]
              fn drop(_: i32, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn drop(_: i32, ) { unreachable!() }
            
            unsafe { drop(_handle as i32); }
          }
        }
        
        #[doc(hidden)]
        #[allow(non_snake_case, unused_unsafe)]
        pub unsafe fn _export_async_method_rrr_fff_cabi<T: GuestRrr>(arg0: *mut u8,) -> i32 { unsafe {#[cfg(target_arch="wasm32")]
        _rt::run_ctors_once();wit_bindgen::rt::async_support::start_task(async move {
          let _task_cancel = wit_bindgen::rt::async_support::TaskCancelOnDrop::new();
          {
            T::fff(&RrrBorrow::lift(arg0 as u32 as usize)).await
          };

          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "[export]wha:hoo/iii")]
          unsafe extern "C" {
            #[link_name = "[task-return][async method]rrr.fff"]
            fn wit_import0();
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import0() { unreachable!() }
          _task_cancel.forget();
          wit_import0();
        })
      } }
      #[doc(hidden)]
      #[allow(non_snake_case)]
      pub unsafe fn __callback_async_method_rrr_fff(event0: u32, event1: u32, event2: u32) -> u32 {
        unsafe {
          wit_bindgen::rt::async_support::callback(event0, event1, event2)
        }
      }
      pub trait Guest {
        type Rrr: GuestRrr;
      }
      pub trait GuestRrr: 'static {

        #[doc(hidden)]
        unsafe fn _resource_new(val: *mut u8) -> u32
        where Self: Sized
        {
          
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "[export]wha:hoo/iii")]
          unsafe extern "C" {
            #[link_name = "[resource-new]rrr"]
            fn new(_: *mut u8, ) -> i32;
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn new(_: *mut u8, ) -> i32 { unreachable!() }
          
          unsafe { new(val) as u32 }
        }

        #[doc(hidden)]
        fn _resource_rep(handle: u32) -> *mut u8
        where Self: Sized
        {
          
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "[export]wha:hoo/iii")]
          unsafe extern "C" {
            #[link_name = "[resource-rep]rrr"]
            fn rep(_: i32, ) -> *mut u8;
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn rep(_: i32, ) -> *mut u8 { unreachable!() }
          
          unsafe { rep(handle as i32) }
        }

        
        #[allow(async_fn_in_trait)]
        async fn fff(&self,) -> ();
      }
      #[doc(hidden)]

      macro_rules! __export_wha_hoo_iii_cabi{
        ($ty:ident with_types_in $($path_to_types:tt)*) => (const _: () = {

          #[unsafe(export_name = "[async-lift]wha:hoo/iii#[async method]rrr.fff")]
          unsafe extern "C" fn export_async_method_rrr_fff(arg0: *mut u8,) -> i32 {
            unsafe { $($path_to_types)*::_export_async_method_rrr_fff_cabi::<<$ty as $($path_to_types)*::Guest>::Rrr>(arg0) }
          }
          #[unsafe(export_name = "[callback][async-lift]wha:hoo/iii#[async method]rrr.fff")]
          unsafe extern "C" fn _callback_async_method_rrr_fff(event0: u32, event1: u32, event2: u32) -> u32 {
            unsafe {
              $($path_to_types)*::__callback_async_method_rrr_fff(event0, event1, event2)
            }
          }
          
          const _: () = {
            #[doc(hidden)]
            #[unsafe(export_name = "wha:hoo/iii#[dtor]rrr")]
            #[allow(non_snake_case)]
            unsafe extern "C" fn dtor(rep: *mut u8) {
              unsafe {
                $($path_to_types)*::Rrr::dtor::<
                <$ty as $($path_to_types)*::Guest>::Rrr
                >(rep)
              }
            }
          };
          
        };);
      }
      #[doc(hidden)]
      pub(crate) use __export_wha_hoo_iii_cabi;

    }

  }
}
}
mod _rt {
  #![allow(dead_code, clippy::all)]


  use core::fmt;
  use core::marker;
  use core::sync::atomic::{AtomicU32, Ordering::Relaxed};

  /// A type which represents a component model resource, either imported or
  /// exported into this component.
  ///
  /// This is a low-level wrapper which handles the lifetime of the resource
  /// (namely this has a destructor). The `T` provided defines the component model
  /// intrinsics that this wrapper uses.
  ///
  /// One of the chief purposes of this type is to provide `Deref` implementations
  /// to access the underlying data when it is owned.
  ///
  /// This type is primarily used in generated code for exported and imported
  /// resources.
  #[repr(transparent)]
  pub struct Resource<T: WasmResource> {
    // NB: This would ideally be `u32` but it is not. The fact that this has
    // interior mutability is not exposed in the API of this type except for the
    // `take_handle` method which is supposed to in theory be private.
    //
    // This represents, almost all the time, a valid handle value. When it's
    // invalid it's stored as `u32::MAX`.
    handle: AtomicU32,
    _marker: marker::PhantomData<T>,
  }

  /// A trait which all wasm resources implement, namely providing the ability to
  /// drop a resource.
  ///
  /// This generally is implemented by generated code, not user-facing code.
  #[allow(clippy::missing_safety_doc)]
  pub unsafe trait WasmResource {
    /// Invokes the `[resource-drop]...` intrinsic.
    unsafe fn drop(handle: u32);
  }

  impl<T: WasmResource> Resource<T> {
    #[doc(hidden)]
    pub unsafe fn from_handle(handle: u32) -> Self {
      debug_assert!(handle != u32::MAX);
      Self {
        handle: AtomicU32::new(handle),
        _marker: marker::PhantomData,
      }
    }

    /// Takes ownership of the handle owned by `resource`.
    ///
    /// Note that this ideally would be `into_handle` taking `Resource<T>` by
    /// ownership. The code generator does not enable that in all situations,
    /// unfortunately, so this is provided instead.
    ///
    /// Also note that `take_handle` is in theory only ever called on values
    /// owned by a generated function. For example a generated function might
    /// take `Resource<T>` as an argument but then call `take_handle` on a
    /// reference to that argument. In that sense the dynamic nature of
    /// `take_handle` should only be exposed internally to generated code, not
    /// to user code.
    #[doc(hidden)]
    pub fn take_handle(resource: &Resource<T>) -> u32 {
      resource.handle.swap(u32::MAX, Relaxed)
    }

    #[doc(hidden)]
    pub fn handle(resource: &Resource<T>) -> u32 {
      resource.handle.load(Relaxed)
    }
  }

  impl<T: WasmResource> fmt::Debug for Resource<T> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
      f.debug_struct("Resource")
      .field("handle", &self.handle)
      .finish()
    }
  }

  impl<T: WasmResource> Drop for Resource<T> {
    fn drop(&mut self) {
      unsafe {
        match self.handle.load(Relaxed) {
          // If this handle was "taken" then don't do anything in the
          // destructor.
          u32::MAX => {}

          // ... but otherwise do actually destroy it with the imported
          // component model intrinsic as defined through `T`.
          other => T::drop(other),
        }
      }
    }
  }
  pub use alloc_crate::boxed::Box;

  #[cfg(target_arch = "wasm32")]
  pub fn run_ctors_once() {
    wit_bindgen::rt::run_ctors_once();
  }
  extern crate alloc as alloc_crate;
}

/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]

macro_rules! __export_core_impl {
  ($ty:ident) => (self::export!($ty with_types_in self););
  ($ty:ident with_types_in $($path_to_types_root:tt)*) => (
  $($path_to_types_root)*::exports::wha::hoo::iii::__export_wha_hoo_iii_cabi!($ty with_types_in $($path_to_types_root)*::exports::wha::hoo::iii);
  )
}
#[doc(inline)]
pub(crate) use __export_core_impl as export;

#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.42.1:wha:hoo:core:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 212] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07Z\x01A\x02\x01A\x02\x01\
B\x04\x04\0\x03rrr\x03\x01\x01h\0\x01@\x01\x04self\x01\x01\0\x04\0\x15[async\x20\
method]rrr.fff\x01\x02\x04\0\x0bwha:hoo/iii\x05\0\x04\0\x0cwha:hoo/core\x04\0\x0b\
\x0a\x01\0\x04core\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-compon\
ent\x070.232.0\x10wit-bindgen-rust\x060.42.1";

#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
  wit_bindgen::rt::maybe_link_cabi_realloc();
}

