(component
  (type (;0;) (enum "a"))
  (type (;1;) (func (param "x" (type 0))))
  (type (;2;) (func (result (type 0))))
  (type (;3;) (union u32 float32))
  (type (;4;) (func (param "x" (type 3))))
  (type (;5;) (func (result (type 3))))
  (type (;6;) (record))
  (type (;7;) (variant (case "a" unit) (case "b" (type 3)) (case "c" (type 0)) (case "d" string) (case "e" (type 6)) (case "f" unit) (case "g" u32)))
  (type (;8;) (func (param "x" (type 7))))
  (type (;9;) (func (result (type 7))))
  (type (;10;) (func (param "x" bool)))
  (type (;11;) (func (result bool)))
  (type (;12;) (option bool))
  (type (;13;) (tuple))
  (type (;14;) (option (type 13)))
  (type (;15;) (option u32))
  (type (;16;) (option (type 0)))
  (type (;17;) (option float32))
  (type (;18;) (option (type 3)))
  (type (;19;) (option bool))
  (type (;20;) (option (type 19)))
  (type (;21;) (func (param "a" (type 12)) (param "b" (type 14)) (param "c" (type 15)) (param "d" (type 16)) (param "e" (type 17)) (param "f" (type 18)) (param "g" (type 20))))
  (type (;22;) (option bool))
  (type (;23;) (option (type 13)))
  (type (;24;) (option u32))
  (type (;25;) (option (type 0)))
  (type (;26;) (option float32))
  (type (;27;) (option (type 3)))
  (type (;28;) (option bool))
  (type (;29;) (option (type 28)))
  (type (;30;) (tuple (type 22) (type 23) (type 24) (type 25) (type 26) (type 27) (type 29)))
  (type (;31;) (func (result (type 30))))
  (type (;32;) (variant (case "a" s32) (case "b" float32)))
  (type (;33;) (variant (case "a" float64) (case "b" float32)))
  (type (;34;) (variant (case "a" float64) (case "b" u64)))
  (type (;35;) (variant (case "a" u32) (case "b" s64)))
  (type (;36;) (variant (case "a" float32) (case "b" s64)))
  (type (;37;) (tuple float32 u32))
  (type (;38;) (tuple u32 u32))
  (type (;39;) (variant (case "a" (type 37)) (case "b" (type 38))))
  (type (;40;) (tuple (type 32) (type 33) (type 34) (type 35) (type 36) (type 39)))
  (type (;41;) (func (param "a" (type 32)) (param "b" (type 33)) (param "c" (type 34)) (param "d" (type 35)) (param "e" (type 36)) (param "f" (type 39)) (result (type 40))))
  (type (;42;) (expected unit unit))
  (type (;43;) (expected unit (type 0)))
  (type (;44;) (expected (type 0) unit))
  (type (;45;) (expected (type 13) (type 13)))
  (type (;46;) (expected u32 (type 7)))
  (type (;47;) (list u8))
  (type (;48;) (expected string (type 47)))
  (type (;49;) (func (param "a" (type 42)) (param "b" (type 43)) (param "c" (type 44)) (param "d" (type 45)) (param "e" (type 46)) (param "f" (type 48))))
  (type (;50;) (expected unit unit))
  (type (;51;) (expected unit (type 0)))
  (type (;52;) (expected (type 0) unit))
  (type (;53;) (expected (type 13) (type 13)))
  (type (;54;) (expected u32 (type 7)))
  (type (;55;) (expected string (type 47)))
  (type (;56;) (tuple (type 50) (type 51) (type 52) (type 53) (type 54) (type 55)))
  (type (;57;) (func (result (type 56))))
  (type (;58;) (enum "bad1" "bad2"))
  (type (;59;) (expected s32 (type 58)))
  (type (;60;) (func (result (type 59))))
  (type (;61;) (expected unit (type 58)))
  (type (;62;) (func (result (type 61))))
  (type (;63;) (expected (type 58) (type 58)))
  (type (;64;) (func (result (type 63))))
  (type (;65;) (tuple s32 u32))
  (type (;66;) (expected (type 65) (type 58)))
  (type (;67;) (func (result (type 66))))
  (type (;68;) (option s32))
  (type (;69;) (func (result (type 68))))
  (type (;70;) (option (type 58)))
  (type (;71;) (func (result (type 70))))
  (type (;72;) (expected u32 s32))
  (type (;73;) (func (result (type 72))))
  (export "e1" (type 0))
  (export "e1-arg" (type 1))
  (export "e1-result" (type 2))
  (export "u1" (type 3))
  (export "u1-arg" (type 4))
  (export "u1-result" (type 5))
  (export "empty" (type 6))
  (export "v1" (type 7))
  (export "v1-arg" (type 8))
  (export "v1-result" (type 9))
  (export "bool-arg" (type 10))
  (export "bool-result" (type 11))
  (export "option-arg" (type 21))
  (export "option-result" (type 31))
  (export "casts1" (type 32))
  (export "casts2" (type 33))
  (export "casts3" (type 34))
  (export "casts4" (type 35))
  (export "casts5" (type 36))
  (export "casts6" (type 39))
  (export "casts" (type 41))
  (export "expected-arg" (type 49))
  (export "expected-result" (type 57))
  (export "my-errno" (type 58))
  (export "return-expected-sugar" (type 60))
  (export "return-expected-sugar2" (type 62))
  (export "return-expected-sugar3" (type 64))
  (export "return-expected-sugar4" (type 67))
  (export "return-option-sugar" (type 69))
  (export "return-option-sugar2" (type 71))
  (export "expected-simple" (type 73))
)