package test:resource-borrow-import;

interface test {
  resource thing {
    constructor(v: u32);
  }

  foo: func(v: borrow<thing>) -> u32;
}

world resource-borrow-import {
  import test;

  export test: func(v: u32) -> u32;
}
