// Generated by `wit-bindgen` 0.37.0. DO NOT EDIT!
// Options used:
#[allow(dead_code, clippy::all)]
pub mod symmetric {
    pub mod runtime {
        /// This interface will only work with symmetric ABI (shared everything),
        /// it can't be composed with the canonical ABI
        /// Asynchronous executor functionality for symmetric ABI
        #[allow(dead_code, unused_imports, clippy::all)]
        pub mod symmetric_executor {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() =
                super::super::super::__link_custom_section_describing_imports;

            use super::super::super::_rt;
            /// These pseudo-resources are just used to
            /// pass pointers to register
            /// This wraps a user provided function of type
            /// `fn (callback-data) -> callback-state`

            #[derive(Debug)]
            #[repr(transparent)]
            pub struct CallbackFunction {
                handle: _rt::Resource<CallbackFunction>,
            }

            impl CallbackFunction {
                #[doc(hidden)]
                pub unsafe fn from_handle(handle: usize) -> Self {
                    Self {
                        handle: _rt::Resource::from_handle(handle),
                    }
                }

                #[doc(hidden)]
                pub fn take_handle(&self) -> usize {
                    _rt::Resource::take_handle(&self.handle)
                }

                #[doc(hidden)]
                pub fn handle(&self) -> usize {
                    _rt::Resource::handle(&self.handle)
                }
            }

            unsafe impl _rt::WasmResource for CallbackFunction {
                #[inline]
                unsafe fn drop(_handle: usize) {
                    {
                        #[link(wasm_import_module = "symmetric:runtime/symmetric-executor@0.1.0")]
                        extern "C" {
                            #[cfg_attr(
                                target_arch = "wasm32",
                                link_name = "[resource-drop]callback-function"
                            )]
                            fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E1X2E0X00X5Bresource_dropX5Dcallback_function(
                                _: usize,
                            );
                        }

                        symmetricX3AruntimeX2Fsymmetric_executorX400X2E1X2E0X00X5Bresource_dropX5Dcallback_function(_handle);
                    }
                }
            }

            /// This wraps opaque user data, freed by the callback once
            /// it returns ready

            #[derive(Debug)]
            #[repr(transparent)]
            pub struct CallbackData {
                handle: _rt::Resource<CallbackData>,
            }

            impl CallbackData {
                #[doc(hidden)]
                pub unsafe fn from_handle(handle: usize) -> Self {
                    Self {
                        handle: _rt::Resource::from_handle(handle),
                    }
                }

                #[doc(hidden)]
                pub fn take_handle(&self) -> usize {
                    _rt::Resource::take_handle(&self.handle)
                }

                #[doc(hidden)]
                pub fn handle(&self) -> usize {
                    _rt::Resource::handle(&self.handle)
                }
            }

            unsafe impl _rt::WasmResource for CallbackData {
                #[inline]
                unsafe fn drop(_handle: usize) {
                    {
                        #[link(wasm_import_module = "symmetric:runtime/symmetric-executor@0.1.0")]
                        extern "C" {
                            #[cfg_attr(
                                target_arch = "wasm32",
                                link_name = "[resource-drop]callback-data"
                            )]
                            fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E1X2E0X00X5Bresource_dropX5Dcallback_data(
                                _: usize,
                            );
                        }

                        symmetricX3AruntimeX2Fsymmetric_executorX400X2E1X2E0X00X5Bresource_dropX5Dcallback_data(_handle);
                    }
                }
            }

            /// The receiving side of an event

            #[derive(Debug)]
            #[repr(transparent)]
            pub struct EventSubscription {
                handle: _rt::Resource<EventSubscription>,
            }

            impl EventSubscription {
                #[doc(hidden)]
                pub unsafe fn from_handle(handle: usize) -> Self {
                    Self {
                        handle: _rt::Resource::from_handle(handle),
                    }
                }

                #[doc(hidden)]
                pub fn take_handle(&self) -> usize {
                    _rt::Resource::take_handle(&self.handle)
                }

                #[doc(hidden)]
                pub fn handle(&self) -> usize {
                    _rt::Resource::handle(&self.handle)
                }
            }

            unsafe impl _rt::WasmResource for EventSubscription {
                #[inline]
                unsafe fn drop(_handle: usize) {
                    {
                        #[link(wasm_import_module = "symmetric:runtime/symmetric-executor@0.1.0")]
                        extern "C" {
                            #[cfg_attr(
                                target_arch = "wasm32",
                                link_name = "[resource-drop]event-subscription"
                            )]
                            fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E1X2E0X00X5Bresource_dropX5Devent_subscription(
                                _: usize,
                            );
                        }

                        symmetricX3AruntimeX2Fsymmetric_executorX400X2E1X2E0X00X5Bresource_dropX5Devent_subscription(_handle);
                    }
                }
            }

            /// A user controlled event

            #[derive(Debug)]
            #[repr(transparent)]
            pub struct EventGenerator {
                handle: _rt::Resource<EventGenerator>,
            }

            impl EventGenerator {
                #[doc(hidden)]
                pub unsafe fn from_handle(handle: usize) -> Self {
                    Self {
                        handle: _rt::Resource::from_handle(handle),
                    }
                }

                #[doc(hidden)]
                pub fn take_handle(&self) -> usize {
                    _rt::Resource::take_handle(&self.handle)
                }

                #[doc(hidden)]
                pub fn handle(&self) -> usize {
                    _rt::Resource::handle(&self.handle)
                }
            }

            unsafe impl _rt::WasmResource for EventGenerator {
                #[inline]
                unsafe fn drop(_handle: usize) {
                    {
                        #[link(wasm_import_module = "symmetric:runtime/symmetric-executor@0.1.0")]
                        extern "C" {
                            #[cfg_attr(
                                target_arch = "wasm32",
                                link_name = "[resource-drop]event-generator"
                            )]
                            fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E1X2E0X00X5Bresource_dropX5Devent_generator(
                                _: usize,
                            );
                        }

                        symmetricX3AruntimeX2Fsymmetric_executorX400X2E1X2E0X00X5Bresource_dropX5Devent_generator(_handle);
                    }
                }
            }

            /// Return value of an async call, lowest bit encoding
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum CallStatus {
                /// For symmetric this means that processing has started, parameters should still remain valid until null,
                /// params-read = non-null, results-written,done = null
                Started,
                /// For symmetric: Retry the call (temporarily out of memory)
                NotStarted,
            }
            impl ::core::fmt::Debug for CallStatus {
                fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                    match self {
                        CallStatus::Started => f.debug_tuple("CallStatus::Started").finish(),
                        CallStatus::NotStarted => f.debug_tuple("CallStatus::NotStarted").finish(),
                    }
                }
            }

            impl CallStatus {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> CallStatus {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }

                    match val {
                        0 => CallStatus::Started,
                        1 => CallStatus::NotStarted,

                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }

            /// Return value of an event callback
            #[repr(u8)]
            #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
            pub enum CallbackState {
                /// Call the function again
                Pending,
                /// The function has completed, all results are written, data is freed,
                /// calling the function again is not permitted as data became invalid!
                Ready,
            }
            impl ::core::fmt::Debug for CallbackState {
                fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                    match self {
                        CallbackState::Pending => f.debug_tuple("CallbackState::Pending").finish(),
                        CallbackState::Ready => f.debug_tuple("CallbackState::Ready").finish(),
                    }
                }
            }

            impl CallbackState {
                #[doc(hidden)]
                pub unsafe fn _lift(val: u8) -> CallbackState {
                    if !cfg!(debug_assertions) {
                        return ::core::mem::transmute(val);
                    }

                    match val {
                        0 => CallbackState::Pending,
                        1 => CallbackState::Ready,

                        _ => panic!("invalid enum discriminant"),
                    }
                }
            }

            impl EventSubscription {
                #[allow(unused_unsafe, clippy::all)]
                /// Whether the event is active (used by poll implementation)
                pub fn ready(&self) -> bool {
                    unsafe {
                        #[link(wasm_import_module = "symmetric:runtime/symmetric-executor@0.1.0")]
                        extern "C" {
                            #[cfg_attr(
                                target_arch = "wasm32",
                                link_name = "[method]event-subscription.ready"
                            )]
                            fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E1X2E0X00X5BmethodX5Devent_subscriptionX2Eready(
                                _: *mut u8,
                            ) -> i32;
                        }
                        let ret = symmetricX3AruntimeX2Fsymmetric_executorX400X2E1X2E0X00X5BmethodX5Devent_subscriptionX2Eready((self).handle() as *mut u8);
                        _rt::bool_lift(ret as u8)
                    }
                }
            }
            impl EventSubscription {
                #[allow(unused_unsafe, clippy::all)]
                /// Create a timeout event
                pub fn from_timeout(nanoseconds: u64) -> EventSubscription {
                    unsafe {
                        #[link(wasm_import_module = "symmetric:runtime/symmetric-executor@0.1.0")]
                        extern "C" {
                            #[cfg_attr(
                                target_arch = "wasm32",
                                link_name = "[static]event-subscription.from-timeout"
                            )]
                            fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E1X2E0X00X5BstaticX5Devent_subscriptionX2Efrom_timeout(
                                _: i64,
                            ) -> *mut u8;
                        }
                        let ret = symmetricX3AruntimeX2Fsymmetric_executorX400X2E1X2E0X00X5BstaticX5Devent_subscriptionX2Efrom_timeout(_rt::as_i64(&nanoseconds));
                        EventSubscription::from_handle(ret as usize)
                    }
                }
            }
            impl EventSubscription {
                #[allow(unused_unsafe, clippy::all)]
                /// Duplicate the subscription (e.g. for repeated callback registering, same cost as subscribe)
                pub fn dup(&self) -> EventSubscription {
                    unsafe {
                        #[link(wasm_import_module = "symmetric:runtime/symmetric-executor@0.1.0")]
                        extern "C" {
                            #[cfg_attr(
                                target_arch = "wasm32",
                                link_name = "[method]event-subscription.dup"
                            )]
                            fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E1X2E0X00X5BmethodX5Devent_subscriptionX2Edup(
                                _: *mut u8,
                            ) -> *mut u8;
                        }
                        let ret = symmetricX3AruntimeX2Fsymmetric_executorX400X2E1X2E0X00X5BmethodX5Devent_subscriptionX2Edup((self).handle() as *mut u8);
                        EventSubscription::from_handle(ret as usize)
                    }
                }
            }
            impl EventSubscription {
                #[allow(unused_unsafe, clippy::all)]
                /// Reset subscription to be inactive, only next trigger will ready it
                pub fn reset(&self) -> () {
                    unsafe {
                        #[link(wasm_import_module = "symmetric:runtime/symmetric-executor@0.1.0")]
                        extern "C" {
                            #[cfg_attr(
                                target_arch = "wasm32",
                                link_name = "[method]event-subscription.reset"
                            )]
                            fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E1X2E0X00X5BmethodX5Devent_subscriptionX2Ereset(
                                _: *mut u8,
                            );
                        }
                        symmetricX3AruntimeX2Fsymmetric_executorX400X2E1X2E0X00X5BmethodX5Devent_subscriptionX2Ereset((self).handle() as *mut u8);
                    }
                }
            }
            impl EventGenerator {
                #[allow(unused_unsafe, clippy::all)]
                pub fn new() -> Self {
                    unsafe {
                        #[link(wasm_import_module = "symmetric:runtime/symmetric-executor@0.1.0")]
                        extern "C" {
                            #[cfg_attr(
                                target_arch = "wasm32",
                                link_name = "[constructor]event-generator"
                            )]
                            fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E1X2E0X00X5BconstructorX5Devent_generator(
                            ) -> *mut u8;
                        }
                        let ret = symmetricX3AruntimeX2Fsymmetric_executorX400X2E1X2E0X00X5BconstructorX5Devent_generator();
                        EventGenerator::from_handle(ret as usize)
                    }
                }
            }
            impl EventGenerator {
                #[allow(unused_unsafe, clippy::all)]
                /// Get the receiving side (to pass to other parts of the program)
                pub fn subscribe(&self) -> EventSubscription {
                    unsafe {
                        #[link(wasm_import_module = "symmetric:runtime/symmetric-executor@0.1.0")]
                        extern "C" {
                            #[cfg_attr(
                                target_arch = "wasm32",
                                link_name = "[method]event-generator.subscribe"
                            )]
                            fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E1X2E0X00X5BmethodX5Devent_generatorX2Esubscribe(
                                _: *mut u8,
                            ) -> *mut u8;
                        }
                        let ret = symmetricX3AruntimeX2Fsymmetric_executorX400X2E1X2E0X00X5BmethodX5Devent_generatorX2Esubscribe((self).handle() as *mut u8);
                        EventSubscription::from_handle(ret as usize)
                    }
                }
            }
            impl EventGenerator {
                #[allow(unused_unsafe, clippy::all)]
                /// Trigger all subscribers
                pub fn activate(&self) -> () {
                    unsafe {
                        #[link(wasm_import_module = "symmetric:runtime/symmetric-executor@0.1.0")]
                        extern "C" {
                            #[cfg_attr(
                                target_arch = "wasm32",
                                link_name = "[method]event-generator.activate"
                            )]
                            fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E1X2E0X00X5BmethodX5Devent_generatorX2Eactivate(
                                _: *mut u8,
                            );
                        }
                        symmetricX3AruntimeX2Fsymmetric_executorX400X2E1X2E0X00X5BmethodX5Devent_generatorX2Eactivate((self).handle() as *mut u8);
                    }
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            /// Wait until all registered events have completed
            pub fn run() -> () {
                unsafe {
                    #[link(wasm_import_module = "symmetric:runtime/symmetric-executor@0.1.0")]
                    extern "C" {
                        #[cfg_attr(target_arch = "wasm32", link_name = "run")]
                        fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E1X2E0X00run();
                    }
                    symmetricX3AruntimeX2Fsymmetric_executorX400X2E1X2E0X00run();
                }
            }
            #[allow(unused_unsafe, clippy::all)]
            /// Register a callback for an event
            pub fn register(
                trigger: EventSubscription,
                callback: CallbackFunction,
                data: CallbackData,
            ) -> () {
                unsafe {
                    #[link(wasm_import_module = "symmetric:runtime/symmetric-executor@0.1.0")]
                    extern "C" {
                        #[cfg_attr(target_arch = "wasm32", link_name = "register")]
                        fn symmetricX3AruntimeX2Fsymmetric_executorX400X2E1X2E0X00register(
                            _: *mut u8,
                            _: *mut u8,
                            _: *mut u8,
                        );
                    }
                    symmetricX3AruntimeX2Fsymmetric_executorX400X2E1X2E0X00register(
                        (&trigger).take_handle() as *mut u8,
                        (&callback).take_handle() as *mut u8,
                        (&data).take_handle() as *mut u8,
                    );
                }
            }
        }
    }
}
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod symmetric {
        pub mod runtime {
            /// language neutral stream implementation
            #[allow(dead_code, unused_imports, clippy::all)]
            pub mod symmetric_stream {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() =
                    super::super::super::super::__link_custom_section_describing_imports;

                use super::super::super::super::_rt;
                pub type EventSubscription = super::super::super::super::symmetric::runtime::symmetric_executor::EventSubscription;

                #[derive(Debug)]
                #[repr(transparent)]
                pub struct Address {
                    handle: _rt::Resource<Address>,
                }

                type _AddressRep<T> = Option<T>;

                impl Address {
                    /// Creates a new resource from the specified representation.
                    ///
                    /// This function will create a new resource handle by moving `val` onto
                    /// the heap and then passing that heap pointer to the component model to
                    /// create a handle. The owned handle is then returned as `Address`.
                    pub fn new<T: GuestAddress>(val: T) -> Self {
                        Self::type_guard::<T>();
                        let val: _AddressRep<T> = Some(val);
                        let ptr: *mut _AddressRep<T> = _rt::Box::into_raw(_rt::Box::new(val));
                        unsafe { Self::from_handle(T::_resource_new(ptr.cast())) }
                    }

                    /// Gets access to the underlying `T` which represents this resource.
                    pub fn get<T: GuestAddress>(&self) -> &T {
                        let ptr = unsafe { &*self.as_ptr::<T>() };
                        ptr.as_ref().unwrap()
                    }

                    /// Gets mutable access to the underlying `T` which represents this
                    /// resource.
                    pub fn get_mut<T: GuestAddress>(&mut self) -> &mut T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.as_mut().unwrap()
                    }

                    /// Consumes this resource and returns the underlying `T`.
                    pub fn into_inner<T: GuestAddress>(self) -> T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.take().unwrap()
                    }

                    #[doc(hidden)]
                    pub unsafe fn from_handle(handle: usize) -> Self {
                        Self {
                            handle: _rt::Resource::from_handle(handle),
                        }
                    }

                    #[doc(hidden)]
                    pub fn take_handle(&self) -> usize {
                        _rt::Resource::take_handle(&self.handle)
                    }

                    #[doc(hidden)]
                    pub fn handle(&self) -> usize {
                        _rt::Resource::handle(&self.handle)
                    }

                    // It's theoretically possible to implement the `GuestAddress` trait twice
                    // so guard against using it with two different types here.
                    #[doc(hidden)]
                    fn type_guard<T: 'static>() {
                        use core::any::TypeId;
                        static mut LAST_TYPE: Option<TypeId> = None;
                        unsafe {
                            assert!(!cfg!(target_feature = "atomics"));
                            let id = TypeId::of::<T>();
                            match LAST_TYPE {
                                Some(ty) => assert!(
                                    ty == id,
                                    "cannot use two types with this resource type"
                                ),
                                None => LAST_TYPE = Some(id),
                            }
                        }
                    }

                    #[doc(hidden)]
                    pub unsafe fn dtor<T: 'static>(handle: *mut u8) {
                        Self::type_guard::<T>();
                        let _ = _rt::Box::from_raw(handle as *mut _AddressRep<T>);
                    }

                    fn as_ptr<T: GuestAddress>(&self) -> *mut _AddressRep<T> {
                        Address::type_guard::<T>();
                        T::_resource_rep(self.handle()).cast()
                    }
                }

                /// A borrowed version of [`Address`] which represents a borrowed value
                /// with the lifetime `'a`.
                #[derive(Debug)]
                #[repr(transparent)]
                pub struct AddressBorrow<'a> {
                    rep: *mut u8,
                    _marker: core::marker::PhantomData<&'a Address>,
                }

                impl<'a> AddressBorrow<'a> {
                    #[doc(hidden)]
                    pub unsafe fn lift(rep: usize) -> Self {
                        Self {
                            rep: rep as *mut u8,
                            _marker: core::marker::PhantomData,
                        }
                    }

                    /// Gets access to the underlying `T` in this resource.
                    pub fn get<T: GuestAddress>(&self) -> &T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.as_ref().unwrap()
                    }

                    // NB: mutable access is not allowed due to the component model allowing
                    // multiple borrows of the same resource.

                    fn as_ptr<T: 'static>(&self) -> *mut _AddressRep<T> {
                        Address::type_guard::<T>();
                        self.rep.cast()
                    }
                }

                unsafe impl _rt::WasmResource for Address {
                    #[inline]
                    unsafe fn drop(_handle: usize) {
                        {
                            #[link(wasm_import_module = "symmetric:runtime/symmetric-stream@0.1.0")]
                            extern "C" {
                                #[cfg_attr(
                                    target_arch = "wasm32",
                                    link_name = "[resource-drop]address"
                                )]
                                fn symmetricX3AruntimeX2Fsymmetric_streamX400X2E1X2E0X00X5Bresource_dropX5Daddress(
                                    _: usize,
                                );
                            }

                            symmetricX3AruntimeX2Fsymmetric_streamX400X2E1X2E0X00X5Bresource_dropX5Daddress(_handle);
                        }
                    }
                }

                /// special zero allocation/copy data type (caller provided buffer)

                #[derive(Debug)]
                #[repr(transparent)]
                pub struct Buffer {
                    handle: _rt::Resource<Buffer>,
                }

                type _BufferRep<T> = Option<T>;

                impl Buffer {
                    /// Creates a new resource from the specified representation.
                    ///
                    /// This function will create a new resource handle by moving `val` onto
                    /// the heap and then passing that heap pointer to the component model to
                    /// create a handle. The owned handle is then returned as `Buffer`.
                    pub fn new<T: GuestBuffer>(val: T) -> Self {
                        Self::type_guard::<T>();
                        let val: _BufferRep<T> = Some(val);
                        let ptr: *mut _BufferRep<T> = _rt::Box::into_raw(_rt::Box::new(val));
                        unsafe { Self::from_handle(T::_resource_new(ptr.cast())) }
                    }

                    /// Gets access to the underlying `T` which represents this resource.
                    pub fn get<T: GuestBuffer>(&self) -> &T {
                        let ptr = unsafe { &*self.as_ptr::<T>() };
                        ptr.as_ref().unwrap()
                    }

                    /// Gets mutable access to the underlying `T` which represents this
                    /// resource.
                    pub fn get_mut<T: GuestBuffer>(&mut self) -> &mut T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.as_mut().unwrap()
                    }

                    /// Consumes this resource and returns the underlying `T`.
                    pub fn into_inner<T: GuestBuffer>(self) -> T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.take().unwrap()
                    }

                    #[doc(hidden)]
                    pub unsafe fn from_handle(handle: usize) -> Self {
                        Self {
                            handle: _rt::Resource::from_handle(handle),
                        }
                    }

                    #[doc(hidden)]
                    pub fn take_handle(&self) -> usize {
                        _rt::Resource::take_handle(&self.handle)
                    }

                    #[doc(hidden)]
                    pub fn handle(&self) -> usize {
                        _rt::Resource::handle(&self.handle)
                    }

                    // It's theoretically possible to implement the `GuestBuffer` trait twice
                    // so guard against using it with two different types here.
                    #[doc(hidden)]
                    fn type_guard<T: 'static>() {
                        use core::any::TypeId;
                        static mut LAST_TYPE: Option<TypeId> = None;
                        unsafe {
                            assert!(!cfg!(target_feature = "atomics"));
                            let id = TypeId::of::<T>();
                            match LAST_TYPE {
                                Some(ty) => assert!(
                                    ty == id,
                                    "cannot use two types with this resource type"
                                ),
                                None => LAST_TYPE = Some(id),
                            }
                        }
                    }

                    #[doc(hidden)]
                    pub unsafe fn dtor<T: 'static>(handle: *mut u8) {
                        Self::type_guard::<T>();
                        let _ = _rt::Box::from_raw(handle as *mut _BufferRep<T>);
                    }

                    fn as_ptr<T: GuestBuffer>(&self) -> *mut _BufferRep<T> {
                        Buffer::type_guard::<T>();
                        T::_resource_rep(self.handle()).cast()
                    }
                }

                /// A borrowed version of [`Buffer`] which represents a borrowed value
                /// with the lifetime `'a`.
                #[derive(Debug)]
                #[repr(transparent)]
                pub struct BufferBorrow<'a> {
                    rep: *mut u8,
                    _marker: core::marker::PhantomData<&'a Buffer>,
                }

                impl<'a> BufferBorrow<'a> {
                    #[doc(hidden)]
                    pub unsafe fn lift(rep: usize) -> Self {
                        Self {
                            rep: rep as *mut u8,
                            _marker: core::marker::PhantomData,
                        }
                    }

                    /// Gets access to the underlying `T` in this resource.
                    pub fn get<T: GuestBuffer>(&self) -> &T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.as_ref().unwrap()
                    }

                    // NB: mutable access is not allowed due to the component model allowing
                    // multiple borrows of the same resource.

                    fn as_ptr<T: 'static>(&self) -> *mut _BufferRep<T> {
                        Buffer::type_guard::<T>();
                        self.rep.cast()
                    }
                }

                unsafe impl _rt::WasmResource for Buffer {
                    #[inline]
                    unsafe fn drop(_handle: usize) {
                        {
                            #[link(wasm_import_module = "symmetric:runtime/symmetric-stream@0.1.0")]
                            extern "C" {
                                #[cfg_attr(
                                    target_arch = "wasm32",
                                    link_name = "[resource-drop]buffer"
                                )]
                                fn symmetricX3AruntimeX2Fsymmetric_streamX400X2E1X2E0X00X5Bresource_dropX5Dbuffer(
                                    _: usize,
                                );
                            }

                            symmetricX3AruntimeX2Fsymmetric_streamX400X2E1X2E0X00X5Bresource_dropX5Dbuffer(_handle);
                        }
                    }
                }

                #[derive(Debug)]
                #[repr(transparent)]
                pub struct StreamObj {
                    handle: _rt::Resource<StreamObj>,
                }

                type _StreamObjRep<T> = Option<T>;

                impl StreamObj {
                    /// Creates a new resource from the specified representation.
                    ///
                    /// This function will create a new resource handle by moving `val` onto
                    /// the heap and then passing that heap pointer to the component model to
                    /// create a handle. The owned handle is then returned as `StreamObj`.
                    pub fn new<T: GuestStreamObj>(val: T) -> Self {
                        Self::type_guard::<T>();
                        let val: _StreamObjRep<T> = Some(val);
                        let ptr: *mut _StreamObjRep<T> = _rt::Box::into_raw(_rt::Box::new(val));
                        unsafe { Self::from_handle(T::_resource_new(ptr.cast())) }
                    }

                    /// Gets access to the underlying `T` which represents this resource.
                    pub fn get<T: GuestStreamObj>(&self) -> &T {
                        let ptr = unsafe { &*self.as_ptr::<T>() };
                        ptr.as_ref().unwrap()
                    }

                    /// Gets mutable access to the underlying `T` which represents this
                    /// resource.
                    pub fn get_mut<T: GuestStreamObj>(&mut self) -> &mut T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.as_mut().unwrap()
                    }

                    /// Consumes this resource and returns the underlying `T`.
                    pub fn into_inner<T: GuestStreamObj>(self) -> T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.take().unwrap()
                    }

                    #[doc(hidden)]
                    pub unsafe fn from_handle(handle: usize) -> Self {
                        Self {
                            handle: _rt::Resource::from_handle(handle),
                        }
                    }

                    #[doc(hidden)]
                    pub fn take_handle(&self) -> usize {
                        _rt::Resource::take_handle(&self.handle)
                    }

                    #[doc(hidden)]
                    pub fn handle(&self) -> usize {
                        _rt::Resource::handle(&self.handle)
                    }

                    // It's theoretically possible to implement the `GuestStreamObj` trait twice
                    // so guard against using it with two different types here.
                    #[doc(hidden)]
                    fn type_guard<T: 'static>() {
                        use core::any::TypeId;
                        static mut LAST_TYPE: Option<TypeId> = None;
                        unsafe {
                            assert!(!cfg!(target_feature = "atomics"));
                            let id = TypeId::of::<T>();
                            match LAST_TYPE {
                                Some(ty) => assert!(
                                    ty == id,
                                    "cannot use two types with this resource type"
                                ),
                                None => LAST_TYPE = Some(id),
                            }
                        }
                    }

                    #[doc(hidden)]
                    pub unsafe fn dtor<T: 'static>(handle: *mut u8) {
                        Self::type_guard::<T>();
                        let _ = _rt::Box::from_raw(handle as *mut _StreamObjRep<T>);
                    }

                    fn as_ptr<T: GuestStreamObj>(&self) -> *mut _StreamObjRep<T> {
                        StreamObj::type_guard::<T>();
                        T::_resource_rep(self.handle()).cast()
                    }
                }

                /// A borrowed version of [`StreamObj`] which represents a borrowed value
                /// with the lifetime `'a`.
                #[derive(Debug)]
                #[repr(transparent)]
                pub struct StreamObjBorrow<'a> {
                    rep: *mut u8,
                    _marker: core::marker::PhantomData<&'a StreamObj>,
                }

                impl<'a> StreamObjBorrow<'a> {
                    #[doc(hidden)]
                    pub unsafe fn lift(rep: usize) -> Self {
                        Self {
                            rep: rep as *mut u8,
                            _marker: core::marker::PhantomData,
                        }
                    }

                    /// Gets access to the underlying `T` in this resource.
                    pub fn get<T: GuestStreamObj>(&self) -> &T {
                        let ptr = unsafe { &mut *self.as_ptr::<T>() };
                        ptr.as_ref().unwrap()
                    }

                    // NB: mutable access is not allowed due to the component model allowing
                    // multiple borrows of the same resource.

                    fn as_ptr<T: 'static>(&self) -> *mut _StreamObjRep<T> {
                        StreamObj::type_guard::<T>();
                        self.rep.cast()
                    }
                }

                unsafe impl _rt::WasmResource for StreamObj {
                    #[inline]
                    unsafe fn drop(_handle: usize) {
                        {
                            #[link(wasm_import_module = "symmetric:runtime/symmetric-stream@0.1.0")]
                            extern "C" {
                                #[cfg_attr(
                                    target_arch = "wasm32",
                                    link_name = "[resource-drop]stream-obj"
                                )]
                                fn symmetricX3AruntimeX2Fsymmetric_streamX400X2E1X2E0X00X5Bresource_dropX5Dstream_obj(
                                    _: usize,
                                );
                            }

                            symmetricX3AruntimeX2Fsymmetric_streamX400X2E1X2E0X00X5Bresource_dropX5Dstream_obj(_handle);
                        }
                    }
                }

                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_constructor_buffer_cabi<T: GuestBuffer>(
                    arg0: *mut u8,
                    arg1: i64,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")]
                    _rt::run_ctors_once();
                    let result0 =
                        Buffer::new(T::new(Address::from_handle(arg0 as usize), arg1 as u64));
                    (result0).take_handle() as *mut u8
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_buffer_get_address_cabi<T: GuestBuffer>(
                    arg0: *mut u8,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")]
                    _rt::run_ctors_once();
                    let result0 = T::get_address(BufferBorrow::lift(arg0 as usize).get());
                    (result0).take_handle() as *mut u8
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_buffer_get_size_cabi<T: GuestBuffer>(
                    arg0: *mut u8,
                ) -> i64 {
                    #[cfg(target_arch = "wasm32")]
                    _rt::run_ctors_once();
                    let result0 = T::get_size(BufferBorrow::lift(arg0 as usize).get());
                    _rt::as_i64(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_buffer_set_size_cabi<T: GuestBuffer>(
                    arg0: *mut u8,
                    arg1: i64,
                ) {
                    #[cfg(target_arch = "wasm32")]
                    _rt::run_ctors_once();
                    T::set_size(BufferBorrow::lift(arg0 as usize).get(), arg1 as u64);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_buffer_capacity_cabi<T: GuestBuffer>(
                    arg0: *mut u8,
                ) -> i64 {
                    #[cfg(target_arch = "wasm32")]
                    _rt::run_ctors_once();
                    let result0 = T::capacity(BufferBorrow::lift(arg0 as usize).get());
                    _rt::as_i64(result0)
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_constructor_stream_obj_cabi<T: GuestStreamObj>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")]
                    _rt::run_ctors_once();
                    let result0 = StreamObj::new(T::new());
                    (result0).take_handle() as *mut u8
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_stream_obj_clone_cabi<T: GuestStreamObj>(
                    arg0: *mut u8,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")]
                    _rt::run_ctors_once();
                    let result0 = T::clone(StreamObjBorrow::lift(arg0 as usize).get());
                    (result0).take_handle() as *mut u8
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_stream_obj_is_write_closed_cabi<T: GuestStreamObj>(
                    arg0: *mut u8,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")]
                    _rt::run_ctors_once();
                    let result0 = T::is_write_closed(StreamObjBorrow::lift(arg0 as usize).get());
                    match result0 {
                        true => 1,
                        false => 0,
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_stream_obj_start_reading_cabi<T: GuestStreamObj>(
                    arg0: *mut u8,
                    arg1: *mut u8,
                ) {
                    #[cfg(target_arch = "wasm32")]
                    _rt::run_ctors_once();
                    T::start_reading(
                        StreamObjBorrow::lift(arg0 as usize).get(),
                        Buffer::from_handle(arg1 as usize),
                    );
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_stream_obj_write_ready_activate_cabi<
                    T: GuestStreamObj,
                >(
                    arg0: *mut u8,
                ) {
                    #[cfg(target_arch = "wasm32")]
                    _rt::run_ctors_once();
                    T::write_ready_activate(StreamObjBorrow::lift(arg0 as usize).get());
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_stream_obj_read_ready_subscribe_cabi<
                    T: GuestStreamObj,
                >(
                    arg0: *mut u8,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")]
                    _rt::run_ctors_once();
                    let result0 =
                        T::read_ready_subscribe(StreamObjBorrow::lift(arg0 as usize).get());
                    (result0).take_handle() as *mut u8
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_stream_obj_read_result_cabi<T: GuestStreamObj>(
                    arg0: *mut u8,
                    arg1: *mut u8,
                ) {
                    #[cfg(target_arch = "wasm32")]
                    _rt::run_ctors_once();
                    let result0 = T::read_result(StreamObjBorrow::lift(arg0 as usize).get());
                    match result0 {
                        Some(e) => {
                            *arg1.add(0).cast::<u8>() = (1i32) as u8;
                            *arg1
                                .add(core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = (e).take_handle() as *mut u8;
                        }
                        None => {
                            *arg1.add(0).cast::<u8>() = (0i32) as u8;
                        }
                    };
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_stream_obj_is_ready_to_write_cabi<
                    T: GuestStreamObj,
                >(
                    arg0: *mut u8,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")]
                    _rt::run_ctors_once();
                    let result0 = T::is_ready_to_write(StreamObjBorrow::lift(arg0 as usize).get());
                    match result0 {
                        true => 1,
                        false => 0,
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_stream_obj_write_ready_subscribe_cabi<
                    T: GuestStreamObj,
                >(
                    arg0: *mut u8,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")]
                    _rt::run_ctors_once();
                    let result0 =
                        T::write_ready_subscribe(StreamObjBorrow::lift(arg0 as usize).get());
                    (result0).take_handle() as *mut u8
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_stream_obj_start_writing_cabi<T: GuestStreamObj>(
                    arg0: *mut u8,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")]
                    _rt::run_ctors_once();
                    let result0 = T::start_writing(StreamObjBorrow::lift(arg0 as usize).get());
                    (result0).take_handle() as *mut u8
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_stream_obj_finish_writing_cabi<T: GuestStreamObj>(
                    arg0: *mut u8,
                    arg1: i32,
                    arg2: *mut u8,
                ) {
                    #[cfg(target_arch = "wasm32")]
                    _rt::run_ctors_once();
                    T::finish_writing(
                        StreamObjBorrow::lift(arg0 as usize).get(),
                        match arg1 {
                            0 => None,
                            1 => {
                                let e = Buffer::from_handle(arg2 as usize);
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                    );
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_method_stream_obj_read_ready_activate_cabi<
                    T: GuestStreamObj,
                >(
                    arg0: *mut u8,
                ) {
                    #[cfg(target_arch = "wasm32")]
                    _rt::run_ctors_once();
                    T::read_ready_activate(StreamObjBorrow::lift(arg0 as usize).get());
                }
                pub trait Guest {
                    type Address: GuestAddress;
                    type Buffer: GuestBuffer;
                    type StreamObj: GuestStreamObj;
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_drop_address_cabi<T: GuestAddress>(arg0: usize) {
                    #[cfg(target_arch = "wasm32")]
                    _rt::run_ctors_once();
                    Address::dtor::<T>(arg0 as *mut u8);
                }
                pub trait GuestAddress: 'static {
                    #[doc(hidden)]
                    unsafe fn _resource_new(val: *mut u8) -> usize
                    where
                        Self: Sized,
                    {
                        val as usize
                    }

                    #[doc(hidden)]
                    fn _resource_rep(handle: usize) -> *mut u8
                    where
                        Self: Sized,
                    {
                        handle as *mut u8
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_drop_buffer_cabi<T: GuestBuffer>(arg0: usize) {
                    #[cfg(target_arch = "wasm32")]
                    _rt::run_ctors_once();
                    Buffer::dtor::<T>(arg0 as *mut u8);
                }
                pub trait GuestBuffer: 'static {
                    #[doc(hidden)]
                    unsafe fn _resource_new(val: *mut u8) -> usize
                    where
                        Self: Sized,
                    {
                        val as usize
                    }

                    #[doc(hidden)]
                    fn _resource_rep(handle: usize) -> *mut u8
                    where
                        Self: Sized,
                    {
                        handle as *mut u8
                    }

                    fn new(addr: Address, capacity: u64) -> Self;
                    fn get_address(&self) -> Address;
                    fn get_size(&self) -> u64;
                    fn set_size(&self, size: u64) -> ();
                    fn capacity(&self) -> u64;
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_drop_streamObj_cabi<T: GuestStreamObj>(arg0: usize) {
                    #[cfg(target_arch = "wasm32")]
                    _rt::run_ctors_once();
                    StreamObj::dtor::<T>(arg0 as *mut u8);
                }
                pub trait GuestStreamObj: 'static {
                    #[doc(hidden)]
                    unsafe fn _resource_new(val: *mut u8) -> usize
                    where
                        Self: Sized,
                    {
                        val as usize
                    }

                    #[doc(hidden)]
                    fn _resource_rep(handle: usize) -> *mut u8
                    where
                        Self: Sized,
                    {
                        handle as *mut u8
                    }

                    fn new() -> Self;
                    /// create a new instance e.g. for reading or tasks
                    fn clone(&self) -> StreamObj;
                    /// reading (in roughly chronological order)
                    fn is_write_closed(&self) -> bool;
                    fn start_reading(&self, buffer: Buffer) -> ();
                    fn write_ready_activate(&self) -> ();
                    fn read_ready_subscribe(&self) -> EventSubscription;
                    /// none is EOF
                    fn read_result(&self) -> Option<Buffer>;
                    /// writing
                    fn is_ready_to_write(&self) -> bool;
                    fn write_ready_subscribe(&self) -> EventSubscription;
                    fn start_writing(&self) -> Buffer;
                    /// none is EOF
                    fn finish_writing(&self, buffer: Option<Buffer>) -> ();
                    fn read_ready_activate(&self) -> ();
                }
                #[doc(hidden)]

                macro_rules! __export_symmetric_runtime_symmetric_stream_0_1_0_cabi{
  ($ty:ident with_types_in $($path_to_types:tt)*) => (const _: () = {

    #[cfg_attr(target_arch = "wasm32", export_name = "[constructor]buffer")]
    #[cfg_attr(not(target_arch = "wasm32"), no_mangle)]
    unsafe extern "C" fn symmetricX3AruntimeX2Fsymmetric_streamX400X2E1X2E0X00X5BconstructorX5Dbuffer(arg0: *mut u8,arg1: i64,) -> *mut u8 {
      $($path_to_types)*::_export_constructor_buffer_cabi::<<$ty as $($path_to_types)*::Guest>::Buffer>(arg0, arg1)
    }
    #[cfg_attr(target_arch = "wasm32", export_name = "[method]buffer.get-address")]
    #[cfg_attr(not(target_arch = "wasm32"), no_mangle)]
    unsafe extern "C" fn symmetricX3AruntimeX2Fsymmetric_streamX400X2E1X2E0X00X5BmethodX5DbufferX2Eget_address(arg0: *mut u8,) -> *mut u8 {
      $($path_to_types)*::_export_method_buffer_get_address_cabi::<<$ty as $($path_to_types)*::Guest>::Buffer>(arg0)
    }
    #[cfg_attr(target_arch = "wasm32", export_name = "[method]buffer.get-size")]
    #[cfg_attr(not(target_arch = "wasm32"), no_mangle)]
    unsafe extern "C" fn symmetricX3AruntimeX2Fsymmetric_streamX400X2E1X2E0X00X5BmethodX5DbufferX2Eget_size(arg0: *mut u8,) -> i64 {
      $($path_to_types)*::_export_method_buffer_get_size_cabi::<<$ty as $($path_to_types)*::Guest>::Buffer>(arg0)
    }
    #[cfg_attr(target_arch = "wasm32", export_name = "[method]buffer.set-size")]
    #[cfg_attr(not(target_arch = "wasm32"), no_mangle)]
    unsafe extern "C" fn symmetricX3AruntimeX2Fsymmetric_streamX400X2E1X2E0X00X5BmethodX5DbufferX2Eset_size(arg0: *mut u8,arg1: i64,) {
      $($path_to_types)*::_export_method_buffer_set_size_cabi::<<$ty as $($path_to_types)*::Guest>::Buffer>(arg0, arg1)
    }
    #[cfg_attr(target_arch = "wasm32", export_name = "[method]buffer.capacity")]
    #[cfg_attr(not(target_arch = "wasm32"), no_mangle)]
    unsafe extern "C" fn symmetricX3AruntimeX2Fsymmetric_streamX400X2E1X2E0X00X5BmethodX5DbufferX2Ecapacity(arg0: *mut u8,) -> i64 {
      $($path_to_types)*::_export_method_buffer_capacity_cabi::<<$ty as $($path_to_types)*::Guest>::Buffer>(arg0)
    }
    #[cfg_attr(target_arch = "wasm32", export_name = "[constructor]stream-obj")]
    #[cfg_attr(not(target_arch = "wasm32"), no_mangle)]
    unsafe extern "C" fn symmetricX3AruntimeX2Fsymmetric_streamX400X2E1X2E0X00X5BconstructorX5Dstream_obj() -> *mut u8 {
      $($path_to_types)*::_export_constructor_stream_obj_cabi::<<$ty as $($path_to_types)*::Guest>::StreamObj>()
    }
    #[cfg_attr(target_arch = "wasm32", export_name = "[method]stream-obj.clone")]
    #[cfg_attr(not(target_arch = "wasm32"), no_mangle)]
    unsafe extern "C" fn symmetricX3AruntimeX2Fsymmetric_streamX400X2E1X2E0X00X5BmethodX5Dstream_objX2Eclone(arg0: *mut u8,) -> *mut u8 {
      $($path_to_types)*::_export_method_stream_obj_clone_cabi::<<$ty as $($path_to_types)*::Guest>::StreamObj>(arg0)
    }
    #[cfg_attr(target_arch = "wasm32", export_name = "[method]stream-obj.is-write-closed")]
    #[cfg_attr(not(target_arch = "wasm32"), no_mangle)]
    unsafe extern "C" fn symmetricX3AruntimeX2Fsymmetric_streamX400X2E1X2E0X00X5BmethodX5Dstream_objX2Eis_write_closed(arg0: *mut u8,) -> i32 {
      $($path_to_types)*::_export_method_stream_obj_is_write_closed_cabi::<<$ty as $($path_to_types)*::Guest>::StreamObj>(arg0)
    }
    #[cfg_attr(target_arch = "wasm32", export_name = "[method]stream-obj.start-reading")]
    #[cfg_attr(not(target_arch = "wasm32"), no_mangle)]
    unsafe extern "C" fn symmetricX3AruntimeX2Fsymmetric_streamX400X2E1X2E0X00X5BmethodX5Dstream_objX2Estart_reading(arg0: *mut u8,arg1: *mut u8,) {
      $($path_to_types)*::_export_method_stream_obj_start_reading_cabi::<<$ty as $($path_to_types)*::Guest>::StreamObj>(arg0, arg1)
    }
    #[cfg_attr(target_arch = "wasm32", export_name = "[method]stream-obj.write-ready-activate")]
    #[cfg_attr(not(target_arch = "wasm32"), no_mangle)]
    unsafe extern "C" fn symmetricX3AruntimeX2Fsymmetric_streamX400X2E1X2E0X00X5BmethodX5Dstream_objX2Ewrite_ready_activate(arg0: *mut u8,) {
      $($path_to_types)*::_export_method_stream_obj_write_ready_activate_cabi::<<$ty as $($path_to_types)*::Guest>::StreamObj>(arg0)
    }
    #[cfg_attr(target_arch = "wasm32", export_name = "[method]stream-obj.read-ready-subscribe")]
    #[cfg_attr(not(target_arch = "wasm32"), no_mangle)]
    unsafe extern "C" fn symmetricX3AruntimeX2Fsymmetric_streamX400X2E1X2E0X00X5BmethodX5Dstream_objX2Eread_ready_subscribe(arg0: *mut u8,) -> *mut u8 {
      $($path_to_types)*::_export_method_stream_obj_read_ready_subscribe_cabi::<<$ty as $($path_to_types)*::Guest>::StreamObj>(arg0)
    }
    #[cfg_attr(target_arch = "wasm32", export_name = "[method]stream-obj.read-result")]
    #[cfg_attr(not(target_arch = "wasm32"), no_mangle)]
    unsafe extern "C" fn symmetricX3AruntimeX2Fsymmetric_streamX400X2E1X2E0X00X5BmethodX5Dstream_objX2Eread_result(arg0: *mut u8,arg1: *mut u8,) {
      $($path_to_types)*::_export_method_stream_obj_read_result_cabi::<<$ty as $($path_to_types)*::Guest>::StreamObj>(arg0, arg1)
    }
    #[cfg_attr(target_arch = "wasm32", export_name = "[method]stream-obj.is-ready-to-write")]
    #[cfg_attr(not(target_arch = "wasm32"), no_mangle)]
    unsafe extern "C" fn symmetricX3AruntimeX2Fsymmetric_streamX400X2E1X2E0X00X5BmethodX5Dstream_objX2Eis_ready_to_write(arg0: *mut u8,) -> i32 {
      $($path_to_types)*::_export_method_stream_obj_is_ready_to_write_cabi::<<$ty as $($path_to_types)*::Guest>::StreamObj>(arg0)
    }
    #[cfg_attr(target_arch = "wasm32", export_name = "[method]stream-obj.write-ready-subscribe")]
    #[cfg_attr(not(target_arch = "wasm32"), no_mangle)]
    unsafe extern "C" fn symmetricX3AruntimeX2Fsymmetric_streamX400X2E1X2E0X00X5BmethodX5Dstream_objX2Ewrite_ready_subscribe(arg0: *mut u8,) -> *mut u8 {
      $($path_to_types)*::_export_method_stream_obj_write_ready_subscribe_cabi::<<$ty as $($path_to_types)*::Guest>::StreamObj>(arg0)
    }
    #[cfg_attr(target_arch = "wasm32", export_name = "[method]stream-obj.start-writing")]
    #[cfg_attr(not(target_arch = "wasm32"), no_mangle)]
    unsafe extern "C" fn symmetricX3AruntimeX2Fsymmetric_streamX400X2E1X2E0X00X5BmethodX5Dstream_objX2Estart_writing(arg0: *mut u8,) -> *mut u8 {
      $($path_to_types)*::_export_method_stream_obj_start_writing_cabi::<<$ty as $($path_to_types)*::Guest>::StreamObj>(arg0)
    }
    #[cfg_attr(target_arch = "wasm32", export_name = "[method]stream-obj.finish-writing")]
    #[cfg_attr(not(target_arch = "wasm32"), no_mangle)]
    unsafe extern "C" fn symmetricX3AruntimeX2Fsymmetric_streamX400X2E1X2E0X00X5BmethodX5Dstream_objX2Efinish_writing(arg0: *mut u8,arg1: i32,arg2: *mut u8,) {
      $($path_to_types)*::_export_method_stream_obj_finish_writing_cabi::<<$ty as $($path_to_types)*::Guest>::StreamObj>(arg0, arg1, arg2)
    }
    #[cfg_attr(target_arch = "wasm32", export_name = "[method]stream-obj.read-ready-activate")]
    #[cfg_attr(not(target_arch = "wasm32"), no_mangle)]
    unsafe extern "C" fn symmetricX3AruntimeX2Fsymmetric_streamX400X2E1X2E0X00X5BmethodX5Dstream_objX2Eread_ready_activate(arg0: *mut u8,) {
      $($path_to_types)*::_export_method_stream_obj_read_ready_activate_cabi::<<$ty as $($path_to_types)*::Guest>::StreamObj>(arg0)
    }
    #[cfg_attr(not(target_arch = "wasm32"), no_mangle)]
    unsafe extern "C" fn symmetricX3AruntimeX2Fsymmetric_streamX400X2E1X2E0X00X5Bresource_dropX5Daddress(arg0: usize) {
      $($path_to_types)*::_export_drop_address_cabi::<<$ty as $($path_to_types)*::Guest>::Address>(arg0)
    }

    #[cfg_attr(not(target_arch = "wasm32"), no_mangle)]
    unsafe extern "C" fn symmetricX3AruntimeX2Fsymmetric_streamX400X2E1X2E0X00X5Bresource_dropX5Dbuffer(arg0: usize) {
      $($path_to_types)*::_export_drop_buffer_cabi::<<$ty as $($path_to_types)*::Guest>::Buffer>(arg0)
    }

    #[cfg_attr(not(target_arch = "wasm32"), no_mangle)]
    unsafe extern "C" fn symmetricX3AruntimeX2Fsymmetric_streamX400X2E1X2E0X00X5Bresource_dropX5Dstream_obj(arg0: usize) {
      $($path_to_types)*::_export_drop_streamObj_cabi::<<$ty as $($path_to_types)*::Guest>::StreamObj>(arg0)
    }

  };);
}
                #[doc(hidden)]
                pub(crate) use __export_symmetric_runtime_symmetric_stream_0_1_0_cabi;
            }
        }
    }
}
mod _rt {
    #![allow(dead_code, clippy::all)]

    use core::fmt;
    use core::marker;
    use core::sync::atomic::{AtomicUsize, Ordering::Relaxed};

    /// A type which represents a component model resource, either imported or
    /// exported into this component.
    ///
    /// This is a low-level wrapper which handles the lifetime of the resource
    /// (namely this has a destructor). The `T` provided defines the component model
    /// intrinsics that this wrapper uses.
    ///
    /// One of the chief purposes of this type is to provide `Deref` implementations
    /// to access the underlying data when it is owned.
    ///
    /// This type is primarily used in generated code for exported and imported
    /// resources.
    #[repr(transparent)]
    pub struct Resource<T: WasmResource> {
        // NB: This would ideally be `usize` but it is not. The fact that this has
        // interior mutability is not exposed in the API of this type except for the
        // `take_handle` method which is supposed to in theory be private.
        //
        // This represents, almost all the time, a valid handle value. When it's
        // invalid it's stored as `0`.
        handle: AtomicUsize,
        _marker: marker::PhantomData<T>,
    }

    /// A trait which all wasm resources implement, namely providing the ability to
    /// drop a resource.
    ///
    /// This generally is implemented by generated code, not user-facing code.
    #[allow(clippy::missing_safety_doc)]
    pub unsafe trait WasmResource {
        /// Invokes the `[resource-drop]...` intrinsic.
        unsafe fn drop(handle: usize);
    }

    impl<T: WasmResource> Resource<T> {
        #[doc(hidden)]
        pub unsafe fn from_handle(handle: usize) -> Self {
            debug_assert!(handle != 0);
            Self {
                handle: AtomicUsize::new(handle),
                _marker: marker::PhantomData,
            }
        }

        /// Takes ownership of the handle owned by `resource`.
        ///
        /// Note that this ideally would be `into_handle` taking `Resource<T>` by
        /// ownership. The code generator does not enable that in all situations,
        /// unfortunately, so this is provided instead.
        ///
        /// Also note that `take_handle` is in theory only ever called on values
        /// owned by a generated function. For example a generated function might
        /// take `Resource<T>` as an argument but then call `take_handle` on a
        /// reference to that argument. In that sense the dynamic nature of
        /// `take_handle` should only be exposed internally to generated code, not
        /// to user code.
        #[doc(hidden)]
        pub fn take_handle(resource: &Resource<T>) -> usize {
            resource.handle.swap(0, Relaxed)
        }

        #[doc(hidden)]
        pub fn handle(resource: &Resource<T>) -> usize {
            resource.handle.load(Relaxed)
        }
    }

    impl<T: WasmResource> fmt::Debug for Resource<T> {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
            f.debug_struct("Resource")
                .field("handle", &self.handle)
                .finish()
        }
    }

    impl<T: WasmResource> Drop for Resource<T> {
        fn drop(&mut self) {
            unsafe {
                match self.handle.load(Relaxed) {
                    // If this handle was "taken" then don't do anything in the
                    // destructor.
                    0 => {}

                    // ... but otherwise do actually destroy it with the imported
                    // component model intrinsic as defined through `T`.
                    other => T::drop(other),
                }
            }
        }
    }
    pub unsafe fn bool_lift(val: u8) -> bool {
        if cfg!(debug_assertions) {
            match val {
                0 => false,
                1 => true,
                _ => panic!("invalid bool discriminant"),
            }
        } else {
            val != 0
        }
    }

    pub fn as_i64<T: AsI64>(t: T) -> i64 {
        t.as_i64()
    }

    pub trait AsI64 {
        fn as_i64(self) -> i64;
    }

    impl<'a, T: Copy + AsI64> AsI64 for &'a T {
        fn as_i64(self) -> i64 {
            (*self).as_i64()
        }
    }

    impl AsI64 for i64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }

    impl AsI64 for u64 {
        #[inline]
        fn as_i64(self) -> i64 {
            self as i64
        }
    }
    pub use alloc_crate::boxed::Box;

    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen::rt::run_ctors_once();
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            core::hint::unreachable_unchecked()
        }
    }
    extern crate alloc as alloc_crate;
}

/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]

macro_rules! __export_stream_impl_impl {
  ($ty:ident) => (self::export!($ty with_types_in self););
  ($ty:ident with_types_in $($path_to_types_root:tt)*) => (
  $($path_to_types_root)*::exports::symmetric::runtime::symmetric_stream::__export_symmetric_runtime_symmetric_stream_0_1_0_cabi!($ty with_types_in $($path_to_types_root)*::exports::symmetric::runtime::symmetric_stream);
  )
}
#[doc(inline)]
pub(crate) use __export_stream_impl_impl as export;

#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.37.0:symmetric:runtime@0.1.0:stream-impl:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1726] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xbc\x0c\x01A\x02\x01\
A\x05\x01B\x20\x04\0\x11callback-function\x03\x01\x04\0\x0dcallback-data\x03\x01\
\x04\0\x12event-subscription\x03\x01\x04\0\x0fevent-generator\x03\x01\x01m\x02\x07\
started\x0bnot-started\x04\0\x0bcall-status\x03\0\x04\x01m\x02\x07pending\x05rea\
dy\x04\0\x0ecallback-state\x03\0\x06\x01h\x02\x01@\x01\x04self\x08\0\x7f\x04\0\x20\
[method]event-subscription.ready\x01\x09\x01i\x02\x01@\x01\x0bnanosecondsw\0\x0a\
\x04\0'[static]event-subscription.from-timeout\x01\x0b\x01@\x01\x04self\x08\0\x0a\
\x04\0\x1e[method]event-subscription.dup\x01\x0c\x01@\x01\x04self\x08\x01\0\x04\0\
\x20[method]event-subscription.reset\x01\x0d\x01i\x03\x01@\0\0\x0e\x04\0\x1c[con\
structor]event-generator\x01\x0f\x01h\x03\x01@\x01\x04self\x10\0\x0a\x04\0![meth\
od]event-generator.subscribe\x01\x11\x01@\x01\x04self\x10\x01\0\x04\0\x20[method\
]event-generator.activate\x01\x12\x01@\0\x01\0\x04\0\x03run\x01\x13\x01i\0\x01i\x01\
\x01@\x03\x07trigger\x0a\x08callback\x14\x04data\x15\x01\0\x04\0\x08register\x01\
\x16\x03\0*symmetric:runtime/symmetric-executor@0.1.0\x05\0\x02\x03\0\0\x12event\
-subscription\x01B*\x02\x03\x02\x01\x01\x04\0\x12event-subscription\x03\0\0\x04\0\
\x07address\x03\x01\x04\0\x06buffer\x03\x01\x04\0\x0astream-obj\x03\x01\x01i\x02\
\x01i\x03\x01@\x02\x04addr\x05\x08capacityw\0\x06\x04\0\x13[constructor]buffer\x01\
\x07\x01h\x03\x01@\x01\x04self\x08\0\x05\x04\0\x1a[method]buffer.get-address\x01\
\x09\x01@\x01\x04self\x08\0w\x04\0\x17[method]buffer.get-size\x01\x0a\x01@\x02\x04\
self\x08\x04sizew\x01\0\x04\0\x17[method]buffer.set-size\x01\x0b\x04\0\x17[metho\
d]buffer.capacity\x01\x0a\x01i\x04\x01@\0\0\x0c\x04\0\x17[constructor]stream-obj\
\x01\x0d\x01h\x04\x01@\x01\x04self\x0e\0\x0c\x04\0\x18[method]stream-obj.clone\x01\
\x0f\x01@\x01\x04self\x0e\0\x7f\x04\0\"[method]stream-obj.is-write-closed\x01\x10\
\x01@\x02\x04self\x0e\x06buffer\x06\x01\0\x04\0\x20[method]stream-obj.start-read\
ing\x01\x11\x01@\x01\x04self\x0e\x01\0\x04\0'[method]stream-obj.write-ready-acti\
vate\x01\x12\x01i\x01\x01@\x01\x04self\x0e\0\x13\x04\0'[method]stream-obj.read-r\
eady-subscribe\x01\x14\x01k\x06\x01@\x01\x04self\x0e\0\x15\x04\0\x1e[method]stre\
am-obj.read-result\x01\x16\x04\0$[method]stream-obj.is-ready-to-write\x01\x10\x04\
\0([method]stream-obj.write-ready-subscribe\x01\x14\x01@\x01\x04self\x0e\0\x06\x04\
\0\x20[method]stream-obj.start-writing\x01\x17\x01@\x02\x04self\x0e\x06buffer\x15\
\x01\0\x04\0![method]stream-obj.finish-writing\x01\x18\x04\0&[method]stream-obj.\
read-ready-activate\x01\x12\x04\0(symmetric:runtime/symmetric-stream@0.1.0\x05\x02\
\x04\0#symmetric:runtime/stream-impl@0.1.0\x04\0\x0b\x11\x01\0\x0bstream-impl\x03\
\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.223.0\x10wit-\
bindgen-rust\x060.37.0";

#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen::rt::maybe_link_cabi_realloc();
}
