package test:suffix;

interface imports {
  foo: func();
}

world available-imports {
  import imports;
  include test:a/imports;
  include test:b/imports;
}

world required-exports {
  include available-imports;

  export run: func();
}
