test-imports: function()
allocated-bytes: function() -> u32

list-param: function(a: list<u8>)
list-param2: function(a: string)
list-param3: function(a: list<string>)
list-param4: function(a: list<list<string>>)
list-result: function() -> list<u8>
list-result2: function() -> string
list-result3: function() -> list<string>

string-roundtrip: function(a: string) -> string
