test-imports: func()
allocated-bytes: func() -> u32

empty-list-param: func(a: list<u8>)
empty-string-param: func(a: string)
empty-list-result: func() -> list<u8>
empty-string-result: func() -> string

list-param: func(a: list<u8>)
list-param2: func(a: string)
list-param3: func(a: list<string>)
list-param4: func(a: list<list<string>>)
list-result: func() -> list<u8>
list-result2: func() -> string
list-result3: func() -> list<string>

list-roundtrip: func(a: list<u8>) -> list<u8>
string-roundtrip: func(a: string) -> string
