package test:resource-import-and-export;

interface test {
  resource thing {
    constructor(v: u32);

    foo: func() -> u32;
    bar: func(v: u32);

    baz: static func(a: thing, b: thing) -> thing;
  }
}

world resource-import-and-export {
  import test;
  export test;

  use test.{thing};

  import toplevel-import: func(a: thing) -> thing;
  export toplevel-export: func(a: thing) -> thing;
}
