(component
  (type (;0;) (func (param "x" string)))
  (type (;1;) (record (field "a" u8)))
  (type (;2;) (func (param "x" (type 1))))
  (type (;3;) 
    (instance
      (alias outer 1 (type (;0;) 0))
      (export "bar1" (type 0))
      (alias outer 1 (type (;1;) 1))
      (export "x" (type 1))
      (alias outer 1 (type (;2;) 2))
      (export "bar2" (type 2))
    )
  )
  (type (;4;) (func))
  (type (;5;) (func (param "x" u8)))
  (type (;6;) (func (param "x" float32)))
  (type (;7;) 
    (instance
      (alias outer 1 (type (;0;) 4))
      (export "foo1" (type 0))
      (alias outer 1 (type (;1;) 5))
      (export "foo2" (type 1))
      (alias outer 1 (type (;2;) 6))
      (export "foo3" (type 2))
    )
  )
  (module (;0;)
    (type (;0;) (func))
    (type (;1;) (func (param i32)))
    (type (;2;) (func (param f32)))
    (type (;3;) (func (param i32 i32)))
    (type (;4;) (func (param i32 i32 i32 i32) (result i32)))
    (type (;5;) (func (param i32 i32 i32)))
    (import "foo" "foo1" (func (;0;) (type 0)))
    (import "foo" "foo2" (func (;1;) (type 1)))
    (import "foo" "foo3" (func (;2;) (type 2)))
    (import "bar" "bar1" (func (;3;) (type 3)))
    (import "bar" "bar2" (func (;4;) (type 1)))
    (func (;5;) (type 4) (param i32 i32 i32 i32) (result i32)
      unreachable
    )
    (func (;6;) (type 5) (param i32 i32 i32)
      unreachable
    )
    (memory (;0;) 1)
    (export "memory" (memory 0))
    (export "canonical_abi_realloc" (func 5))
    (export "canonical_abi_free" (func 6))
  )
  (import "bar" (instance (;0;) (type 3)))
  (import "foo" (instance (;1;) (type 7)))
  (module (;1;)
    (type (;0;) (func (param i32 i32)))
    (type (;1;) (func (param i32)))
    (type (;2;) (func))
    (type (;3;) (func (param f32)))
    (func (;0;) (type 0) (param i32 i32)
      local.get 0
      local.get 1
      i32.const 0
      call_indirect (type 0)
    )
    (func (;1;) (type 1) (param i32)
      local.get 0
      i32.const 1
      call_indirect (type 1)
    )
    (func (;2;) (type 2)
      i32.const 2
      call_indirect (type 2)
    )
    (func (;3;) (type 1) (param i32)
      local.get 0
      i32.const 3
      call_indirect (type 1)
    )
    (func (;4;) (type 3) (param f32)
      local.get 0
      i32.const 4
      call_indirect (type 3)
    )
    (table (;0;) 5 5 funcref)
    (export "bar1" (func 0))
    (export "bar2" (func 1))
    (export "foo1" (func 2))
    (export "foo2" (func 3))
    (export "foo3" (func 4))
    (export "$imports" (table 0))
  )
  (module (;2;)
    (type (;0;) (func (param i32 i32)))
    (type (;1;) (func (param i32)))
    (type (;2;) (func))
    (type (;3;) (func (param f32)))
    (import "" "bar1" (func (;0;) (type 0)))
    (import "" "bar2" (func (;1;) (type 1)))
    (import "" "foo1" (func (;2;) (type 2)))
    (import "" "foo2" (func (;3;) (type 1)))
    (import "" "foo3" (func (;4;) (type 3)))
    (import "" "$imports" (table (;0;) 5 5 funcref))
    (elem (;0;) (i32.const 0) func 0 1 2 3 4)
  )
  (instance (;2;) (instantiate (module 1)))
  (instance (;3;) (instantiate (module 0) (with "bar" (instance 2)) (with "foo" (instance 2))))
  (alias export (instance 2) "$imports" (table (;0;)))
  (alias export (instance 0) "bar1" (func (;0;)))
  (alias export (instance 0) "bar2" (func (;1;)))
  (alias export (instance 1) "foo1" (func (;2;)))
  (alias export (instance 1) "foo2" (func (;3;)))
  (alias export (instance 1) "foo3" (func (;4;)))
  (func (;5;) (canon.lower utf8 (into (instance 3)) (func 0)))
  (func (;6;) (canon.lower utf8 (into (instance 3)) (func 1)))
  (func (;7;) (canon.lower utf8 (into (instance 3)) (func 2)))
  (func (;8;) (canon.lower utf8 (into (instance 3)) (func 3)))
  (func (;9;) (canon.lower utf8 (into (instance 3)) (func 4)))
  (instance (;4;) core (export "$imports" (table 0)) (export "bar1" (func 5)) (export "bar2" (func 6)) (export "foo1" (func 7)) (export "foo2" (func 8)) (export "foo3" (func 9)))
  (instance (;5;) (instantiate (module 2) (with "" (instance 4))))
)